//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignedRepGroup
    {
        public int RepNumber { get; set; }
        public string RepGroup { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> FKRepGroupID { get; set; }
    
        public virtual tblRepGroup tblRepGroup { get; set; }
        public virtual tblRep tblRep { get; set; }
    }
}
