//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignedContactGroup
    {
        public int ContactNumber { get; set; }
        public string ContactGroup { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual tblContactGroup tblContactGroup { get; set; }
        public virtual tblContact tblContact { get; set; }
    }
}
