//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountSystem
    {
        public int AccountNumber { get; set; }
        public string SystemDescription { get; set; }
        public bool DefaultFlag { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblSystem tblSystem { get; set; }
    }
}
