//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAPIUsersAudit
    {
        public int id { get; set; }
        public System.DateTime DateModified { get; set; }
        public string Action { get; set; }
        public string SysName { get; set; }
        public string HostName { get; set; }
        public string AppName { get; set; }
        public string UserIDOrig { get; set; }
        public string PasswordOrig { get; set; }
        public string UserNameOrig { get; set; }
        public string EmailAddressOrig { get; set; }
        public Nullable<bool> ActiveOrig { get; set; }
        public string PasswordNew { get; set; }
        public string UserNameNew { get; set; }
        public string EmailAddressNew { get; set; }
        public Nullable<bool> ActiveNew { get; set; }
        public string UserIDNew { get; set; }
        public Nullable<int> AcctSecOrig { get; set; }
        public Nullable<int> AcctSecNew { get; set; }
        public Nullable<int> ExternalProductOrig { get; set; }
        public Nullable<int> ExternalProductNew { get; set; }
    }
}
