//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccount()
        {
            this.tblAccountRelations = new HashSet<tblAccountRelation>();
            this.tblAccountSystems = new HashSet<tblAccountSystem>();
            this.tblAltBillToes = new HashSet<tblAltBillTo>();
            this.tblAltShipToes = new HashSet<tblAltShipTo>();
            this.tblAssignedExternalAccounts = new HashSet<tblAssignedExternalAccount>();
            this.tblAssignedAccountProfiles = new HashSet<tblAssignedAccountProfile>();
            this.tblAssignedSICCodes = new HashSet<tblAssignedSICCode>();
            this.tblAutomatedReports = new HashSet<tblAutomatedReport>();
            this.tblCentralBillings = new HashSet<tblCentralBilling>();
            this.tblCircuits = new HashSet<tblCircuit>();
            this.tblContacts = new HashSet<tblContact>();
            this.tblContractCustomers = new HashSet<tblContractCustomer>();
            this.tblCustomerInventories = new HashSet<tblCustomerInventory>();
            this.tblCustomFoldersNotes = new HashSet<tblCustomFoldersNote>();
            this.tblDocuments = new HashSet<tblDocument>();
            this.tblEmailAddresses = new HashSet<tblEmailAddress>();
            this.tblInvoices = new HashSet<tblInvoice>();
            this.tblJournals = new HashSet<tblJournal>();
            this.tblMSPAccountAssets = new HashSet<tblMSPAccountAsset>();
            this.tblMSPAgreements = new HashSet<tblMSPAgreement>();
            this.tblOpportunities = new HashSet<tblOpportunity>();
            this.tblPayMethods = new HashSet<tblPayMethod>();
            this.tblPhoneNumbers = new HashSet<tblPhoneNumber>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblQuotes = new HashSet<tblQuote>();
            this.tblServiceOrders = new HashSet<tblServiceOrder>();
            this.tblTasks = new HashSet<tblTask>();
            this.tblVendorInformations = new HashSet<tblVendorInformation>();
        }
    
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string AccountType { get; set; }
        public string AccountStatus { get; set; }
        public string AccountSource { get; set; }
        public Nullable<System.DateTime> SourceChangedDate { get; set; }
        public bool Inactive { get; set; }
        public int PrimaryContactNumber { get; set; }
        public int RepNumber { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string PrimaryFaxNumber { get; set; }
        public string PrimaryFaxNumberFormatted { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public bool DoNotEmail { get; set; }
        public string URL1 { get; set; }
        public string URL1Description { get; set; }
        public string URL2 { get; set; }
        public string URL2Description { get; set; }
        public decimal SalesVolume { get; set; }
        public string NumberOfEmployees { get; set; }
        public bool SyncAlways { get; set; }
        public string MarketingMemo { get; set; }
        public string QuoteSpecialInstructions { get; set; }
        public string SpecialInstructions { get; set; }
        public string HotNote { get; set; }
        public string ServiceZone { get; set; }
        public int PrimaryShipTo { get; set; }
        public string DirectionsToLocation { get; set; }
        public int PrimaryBillTo { get; set; }
        public bool AddToAR { get; set; }
        public string ARCustomerNumber { get; set; }
        public string AccountingCompanyId { get; set; }
        public string Department { get; set; }
        public bool CreditHold { get; set; }
        public string CreditHoldSpecialInstructions { get; set; }
        public int DefaultContract { get; set; }
        public string DefaultShipMethod { get; set; }
        public int DefaultPriceLevel { get; set; }
        public string DefaultSystem { get; set; }
        public string DefaultPayMethod { get; set; }
        public string DefaultTerms { get; set; }
        public string BOTaxCode { get; set; }
        public string BOTaxType { get; set; }
        public bool TaxFreight { get; set; }
        public string SalesTaxCode { get; set; }
        public string TaxExemptCategory { get; set; }
        public string TaxExemptID { get; set; }
        public bool GSTExempt { get; set; }
        public string GSTaxExemptID { get; set; }
        public bool TaxLabor { get; set; }
        public Nullable<System.DateTime> InitialContact { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public decimal DefaultLaborRate { get; set; }
        public bool ApplyQuantityDiscounts { get; set; }
        public bool IsVendor { get; set; }
        public string AccountNameMetaPhone { get; set; }
        public bool IsSubcontractor { get; set; }
        public Nullable<int> FKMSPID { get; set; }
        public bool TaxGST { get; set; }
        public Nullable<System.DateTime> MSPLastPollingDate { get; set; }
        public int FKNumberOfEmployees { get; set; }
        public string EmployeeNumberRange { get; set; }
        public int DefaultSubContractor { get; set; }
        public Nullable<int> DefaultPayMethodID { get; set; }
        public Nullable<System.DateTime> FirstInvoiceDate { get; set; }
        public Nullable<int> CountOfOpenSOs { get; set; }
        public Nullable<int> AllowedInvoicePaymentLateDays { get; set; }
        public bool ProviderTaxExempt { get; set; }
        public int DefaultServiceTech { get; set; }
        public int FKDefaultDispatchBoard { get; set; }
        public Nullable<long> FKModifiedByRep { get; set; }
        public Nullable<int> FKStatusLableActionsKeyID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LeadScore { get; set; }
        public int FKPayMethods { get; set; }
        public bool EnableCentralBilling { get; set; }
        public bool AlwaysBillParent { get; set; }
        public bool IncludeParentOrdersInCBIInvoices { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountRelation> tblAccountRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountSystem> tblAccountSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAltBillTo> tblAltBillToes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAltShipTo> tblAltShipToes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignedExternalAccount> tblAssignedExternalAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignedAccountProfile> tblAssignedAccountProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignedSICCode> tblAssignedSICCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAutomatedReport> tblAutomatedReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCentralBilling> tblCentralBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCircuit> tblCircuits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContact> tblContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContractCustomer> tblContractCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerInventory> tblCustomerInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomFoldersNote> tblCustomFoldersNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocument> tblDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmailAddress> tblEmailAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJournal> tblJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMSPAccountAsset> tblMSPAccountAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMSPAgreement> tblMSPAgreements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOpportunity> tblOpportunities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayMethod> tblPayMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhoneNumber> tblPhoneNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuote> tblQuotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceOrder> tblServiceOrders { get; set; }
        public virtual tblSubcontractorInformation tblSubcontractorInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTask> tblTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVendorInformation> tblVendorInformations { get; set; }
    }
}
