//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssemblyDetail
    {
        public int AssemblyDetailKeyID { get; set; }
        public string AssemblyHeaderItemID { get; set; }
        public int LineNumber { get; set; }
        public string ItemID { get; set; }
        public float Quantity { get; set; }
        public string Type { get; set; }
        public bool PrintOnQuote { get; set; }
    
        public virtual tblPriceBook tblPriceBook { get; set; }
    }
}
