//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutomatedReportParameter
    {
        public int AutomatedReportParameterID { get; set; }
        public int AutomatedReportID { get; set; }
        public string ParameterName { get; set; }
        public string ParameterType { get; set; }
        public string ParameterValue { get; set; }
        public string DateType { get; set; }
        public string DateRelation { get; set; }
        public bool UseOffset { get; set; }
        public string OffsetInterval { get; set; }
        public Nullable<int> OffsetValue { get; set; }
    
        public virtual tblAutomatedReport tblAutomatedReport { get; set; }
    }
}
