//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAPPOHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAPPOHeader()
        {
            this.tblAPPODetails = new HashSet<tblAPPODetail>();
        }
    
        public int BatchNumber { get; set; }
        public int PoNumber { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public string APVendorID { get; set; }
        public string VendorName { get; set; }
        public decimal PoTotalReceipts { get; set; }
        public decimal Freight { get; set; }
        public decimal PoTotalAmount { get; set; }
        public string POCreditAccountNumber { get; set; }
        public string POCreditDepartment { get; set; }
        public string POReceiptsAccount { get; set; }
        public string POReceiptsDepartment { get; set; }
        public string POFreightAccount { get; set; }
        public string POFreightDepartment { get; set; }
        public int NumberOfDistributions { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string ConfirmedTo { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string BuyerName { get; set; }
        public string BuyerID { get; set; }
        public string Comments { get; set; }
        public string OrderTerms { get; set; }
        public string FreightTerms { get; set; }
        public string ShippingMethod { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhone { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string VendorAddress1 { get; set; }
        public string VendorAddress2 { get; set; }
        public string VendorCity { get; set; }
        public string VendorState { get; set; }
        public string VendorPostalCode { get; set; }
        public string VendorCountry { get; set; }
        public string VendorPhoneNumber { get; set; }
        public string VendorFaxNumber { get; set; }
        public string VendorEmailAddress { get; set; }
        public string VendorContactName { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAPPODetail> tblAPPODetails { get; set; }
    }
}
