//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutomatedReportsConfig
    {
        public int ID { get; set; }
        public string AutoEmailAddress { get; set; }
        public Nullable<int> ErrorInfoRepID { get; set; }
        public string ReportsToEmailDirectory { get; set; }
        public string ProcessorPath { get; set; }
        public Nullable<bool> ProcessorTestMode { get; set; }
        public Nullable<bool> ScheduleSuspended { get; set; }
        public Nullable<System.DateTime> ProcessorTestDate { get; set; }
        public Nullable<int> RepNumber { get; set; }
    }
}
