//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblARTax
    {
        public int ARTaxKeyID { get; set; }
        public int FKARHeader { get; set; }
        public int BatchNumber { get; set; }
        public string SalesTaxCode { get; set; }
        public string SalesTaxDistrict { get; set; }
        public float SalesTaxRate { get; set; }
        public string Account { get; set; }
        public string Department { get; set; }
        public decimal Amount { get; set; }
        public string SalesTaxVendor { get; set; }
    
        public virtual tblARHeader tblARHeader { get; set; }
    }
}
