//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBOTransaction
    {
        public int BOTransactionsKeyID { get; set; }
        public string BOTaxCode { get; set; }
        public string BOTaxType { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int AccountNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public int InvoiceNumber { get; set; }
        public decimal WholesaleTax { get; set; }
        public decimal RetailTax { get; set; }
        public decimal NetInvoiceAmount { get; set; }
        public int CreditMemoNumber { get; set; }
    
        public virtual tblBOTaxCode tblBOTaxCode { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
