//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBOTaxCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBOTaxCode()
        {
            this.tblBOTransactions = new HashSet<tblBOTransaction>();
        }
    
        public string BOTaxCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public float RetailRate { get; set; }
        public float WholesaleRate { get; set; }
        public string RetailGLCode { get; set; }
        public string WholesaleGLCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBOTransaction> tblBOTransactions { get; set; }
    }
}
