//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillCycleDetail
    {
        public int BillCycleDetailKeyID { get; set; }
        public int FKBillCycleTotal { get; set; }
        public int ContractNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ItemID { get; set; }
        public string Description { get; set; }
        public string UsageType { get; set; }
        public decimal OverageQuantity { get; set; }
        public decimal OverageRate { get; set; }
        public decimal OverageDollars { get; set; }
        public int CreditMemoNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public int SONumber { get; set; }
        public short RoundingMinutes { get; set; }
    
        public virtual tblBillCycleTotal tblBillCycleTotal { get; set; }
    }
}
