//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCentralBillingMiscCredit
    {
        public int KeyID { get; set; }
        public int FKCentralBillingCreditMemoKey { get; set; }
        public int CreditMemoNumber { get; set; }
        public string TransactionType { get; set; }
        public decimal TransactionAmount { get; set; }
        public int RepNumber { get; set; }
        public decimal SalesTax { get; set; }
        public decimal GSTax { get; set; }
        public decimal ProviderTax { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public int SourceDocumentNumber { get; set; }
    }
}
