//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerInventory()
        {
            this.tblCustomerInventoryAssemblyDetails = new HashSet<tblCustomerInventoryAssemblyDetail>();
        }
    
        public int CustomerInventoryKeyID { get; set; }
        public int AccountNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string SerialNumber { get; set; }
        public string Status { get; set; }
        public string StatusComment { get; set; }
        public double Quantity { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public bool PurchasedFromUs { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public decimal PurchasePrice { get; set; }
        public Nullable<System.DateTime> WarrantyExpiry { get; set; }
        public Nullable<System.DateTime> LastPMDate { get; set; }
        public int CurrMeterReading { get; set; }
        public int OrigMeterReading { get; set; }
        public Nullable<System.DateTime> NextPMDate { get; set; }
        public int ServicePriority { get; set; }
        public int ContractNumber { get; set; }
        public int FKContractDetail { get; set; }
        public string Location { get; set; }
        public string ContactName { get; set; }
        public int ContactNumber { get; set; }
        public string ContactPhone { get; set; }
        public decimal YearlyMaintPrice { get; set; }
        public Nullable<System.DateTime> DatePurchasedFromVendor { get; set; }
        public Nullable<System.DateTime> MFGWarrantyExpiry { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int TransferTo { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public bool AllowExchange { get; set; }
        public int FKExchange { get; set; }
        public int ItemExchangedFor { get; set; }
        public bool AssemblyFlag { get; set; }
        public string Comments { get; set; }
        public int CreditMemoNumber { get; set; }
        public int FKCreditMemoDetail { get; set; }
        public int FKCreditMemoAssemblyDetail { get; set; }
        public double CreditMemoQuantity { get; set; }
        public int InvoiceNumber { get; set; }
        public int FKInvoiceDetail { get; set; }
        public int FKInvoiceAssemblyDetail { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public int VendorAccountNumber { get; set; }
        public Nullable<System.DateTime> BMFLastProcessed { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> NextActionDate { get; set; }
        public string NextActionType { get; set; }
        public bool NextActionTriggersWorkflow { get; set; }
        public string ReplacedByItemID { get; set; }
        public bool WarrantyExpirationTriggersWorkflow { get; set; }
        public int PrimaryRepNumber { get; set; }
        public bool PrintOnCustomerFacingReports { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerInventoryAssemblyDetail> tblCustomerInventoryAssemblyDetails { get; set; }
    }
}
