//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractCustomer
    {
        public int ContractCustomersKeyID { get; set; }
        public int ContractNumber { get; set; }
        public int AccountNumber { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblContract tblContract { get; set; }
    }
}
