//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCentralBillingWorkTable
    {
        public int CentralBillingWorkTableKeyID { get; set; }
        public int ParentAccountNumber { get; set; }
        public int DocumentType { get; set; }
        public int DocumentNumber { get; set; }
        public int DocumentAccountNumber { get; set; }
        public bool OKToInvoice { get; set; }
        public int ProcessingRep { get; set; }
    }
}
