//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditMemoAssemblyDetail
    {
        public int CreditMemoAssemblyDetailKeyID { get; set; }
        public int FKCreditMemoDetail { get; set; }
        public int CreditMemoNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string InventoryType { get; set; }
        public double EachQuantity { get; set; }
        public double Quantity { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal UnitCreditAmount { get; set; }
        public decimal TotalCreditAmount { get; set; }
        public bool GSTExempt { get; set; }
        public decimal GSTaxableAmount { get; set; }
        public bool Taxable { get; set; }
        public decimal TaxableAmount { get; set; }
        public bool Serialized { get; set; }
        public string CostGLCode { get; set; }
        public string IncomeGLCode { get; set; }
        public decimal ActualUnitCost { get; set; }
        public decimal TotalActualCost { get; set; }
        public int FKInvoiceAssemblyDetail { get; set; }
        public int FKCustomerInventory { get; set; }
        public int FKCustomerInventoryAssemblyDetail { get; set; }
        public bool PrintOnInvoice { get; set; }
        public bool SubjectToProviderTax { get; set; }
        public decimal ProviderTaxableAmount { get; set; }
    
        public virtual tblCreditMemoDetail tblCreditMemoDetail { get; set; }
    }
}
