//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractDetail
    {
        public int ContractDetailKeyID { get; set; }
        public int ContractNumber { get; set; }
        public string Reference { get; set; }
        public int AccountNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string SerialNumber { get; set; }
        public double Quantity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public decimal ContractPrice { get; set; }
        public Nullable<System.DateTime> BilledThruDate { get; set; }
        public decimal BilledToDate { get; set; }
        public decimal YearlyPrice { get; set; }
        public decimal ListPrice { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public float RenewalListPercentage { get; set; }
        public int FKCustomerInventory { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public int FKContractCustomers { get; set; }
        public int PeriodsBilled { get; set; }
        public int StartingMeter { get; set; }
        public int MaxMeter { get; set; }
        public int CurrentMeter { get; set; }
        public int WarningClicks { get; set; }
        public decimal OverageChargePerClick { get; set; }
        public int ClicksCarriedOver { get; set; }
        public int MeterRemaining { get; set; }
        public int PeriodBaseClicks { get; set; }
        public string SOPriority { get; set; }
    
        public virtual tblContract tblContract { get; set; }
    }
}
