//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomFoldersNote
    {
        public int AccountNumber { get; set; }
        public string Category { get; set; }
        public string Folder { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblCustomFoldersFolder tblCustomFoldersFolder { get; set; }
    }
}
