//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDashBoardPanel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDashBoardPanel()
        {
            this.tblDashboardPanelsDefaultFieldDefinitions = new HashSet<tblDashboardPanelsDefaultFieldDefinition>();
        }
    
        public int DashBoardPanelKeyID { get; set; }
        public int PanelType { get; set; }
        public string PanelDescription { get; set; }
        public string StoredProcedure { get; set; }
        public bool PassRepNumber { get; set; }
        public bool ShowRank { get; set; }
        public bool Available { get; set; }
        public string ToolTipText { get; set; }
        public bool IsDrillable { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public int FKCategoryID { get; set; }
    
        public virtual tblDashBoardPanelCategory tblDashBoardPanelCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDashboardPanelsDefaultFieldDefinition> tblDashboardPanelsDefaultFieldDefinitions { get; set; }
    }
}
