//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailTrack_ClickThruLinks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmailTrack_ClickThruLinks()
        {
            this.tblEmailTrack_ClickThru = new HashSet<tblEmailTrack_ClickThru>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string AlternateText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmailTrack_ClickThru> tblEmailTrack_ClickThru { get; set; }
    }
}
