//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailTrack_UnSubscribe
    {
        public int UnSubscribeID { get; set; }
        public int AccountNumber { get; set; }
        public int ContactNumber { get; set; }
        public int FKStatID { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateUnSubscribed { get; set; }
    
        public virtual tblEmailTrack_Stats tblEmailTrack_Stats { get; set; }
    }
}
