//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEZBillWorkTable
    {
        public int EZBillWorkTableKeyID { get; set; }
        public int FKSOLogs { get; set; }
        public string LaborItemKeyID { get; set; }
        public string LaborItemDescription { get; set; }
        public int RateType { get; set; }
        public int RateBasis { get; set; }
        public string RateBasisText { get; set; }
        public decimal LaborRate { get; set; }
        public decimal Quantity { get; set; }
        public int SONumber { get; set; }
        public int RepNumber { get; set; }
        public bool UnderContract { get; set; }
    }
}
