//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFilterAdv
    {
        public int id { get; set; }
        public int cnid { get; set; }
        public int itemtype { get; set; }
        public int action { get; set; }
        public string value { get; set; }
    }
}
