//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGridSettings2
    {
        public int ID { get; set; }
        public int ListViewID { get; set; }
        public string Description { get; set; }
        public int RepNumber { get; set; }
        public string Filter { get; set; }
        public bool IsCurrent { get; set; }
        public string WhereClause { get; set; }
        public string OrderByClause { get; set; }
        public string SelectedAccountGroups { get; set; }
        public string SelectedAccountProfiles { get; set; }
        public string SelectedContactGroups { get; set; }
        public string SelectedContactProfiles { get; set; }
        public string SelectedSICCodes { get; set; }
        public string SelectedSOProfiles { get; set; }
        public string SelectedItemIDs { get; set; }
        public Nullable<int> CurrentPage { get; set; }
        public Nullable<int> CurrentRowNumber { get; set; }
        public Nullable<int> CurrentRowID { get; set; }
    
        public virtual tblRep tblRep { get; set; }
    }
}
