//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGLHeader()
        {
            this.tblGLDetails = new HashSet<tblGLDetail>();
        }
    
        public int GLHeaderKeyID { get; set; }
        public int BatchNumber { get; set; }
        public string AccountingCompanyID { get; set; }
        public string SourceJournal { get; set; }
        public int PostingBatch { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public bool PrintedFlag { get; set; }
        public string Reference { get; set; }
        public int NumberOfDistributions { get; set; }
        public decimal TransactionDebitTotal { get; set; }
        public decimal TransactionCreditTotal { get; set; }
        public int FiscalPeriod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLDetail> tblGLDetails { get; set; }
    }
}
