//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImportProcedure
    {
        public int ID { get; set; }
        public string ImportProcedure { get; set; }
        public string ImportTableDescription { get; set; }
        public string ImportFieldDescription { get; set; }
        public string Value { get; set; }
        public string Comment { get; set; }
        public string ImportTableName { get; set; }
        public string ImportFieldName { get; set; }
        public Nullable<int> ImportFieldType { get; set; }
        public Nullable<int> ImportFieldLength { get; set; }
    }
}
