//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoicePostingAudit
    {
        public string Source { get; set; }
        public int DocumentNumber { get; set; }
        public string DocumentType { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public int BatchNo { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string PartNumber { get; set; }
        public double Quantity { get; set; }
        public decimal TotalSale { get; set; }
        public decimal TotalCost { get; set; }
        public decimal MarginAmount { get; set; }
        public double MarginPercent { get; set; }
        public bool Printed { get; set; }
    }
}
