//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLink()
        {
            this.tblLinkFileDescriptions = new HashSet<tblLinkFileDescription>();
        }
    
        public int LinksKeyID { get; set; }
        public string LinkName { get; set; }
        public string LinkVersionNumber { get; set; }
        public string AccountingSoftware { get; set; }
        public bool AllowEdit { get; set; }
        public bool OutputARDetailTaxFirst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLinkFileDescription> tblLinkFileDescriptions { get; set; }
    }
}
