//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLVDefinition
    {
        public int ListViewID { get; set; }
        public string Description { get; set; }
        public short ItemsPerPage { get; set; }
        public string Primary { get; set; }
        public string PrimaryLinkField { get; set; }
        public string PrimaryDefaultSortField { get; set; }
        public Nullable<bool> PrimaryDefaultSortDirection { get; set; }
        public string Secondary { get; set; }
        public string SecondaryLinkField { get; set; }
        public bool AllowMultipleSelections { get; set; }
        public bool AllowFiltering { get; set; }
        public bool AllowSorting { get; set; }
    }
}
