//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLVAppearenceCondition
    {
        public int ID { get; set; }
        public int FKValAppearence { get; set; }
        public string Description { get; set; }
        public Nullable<byte> ForeColorRed { get; set; }
        public Nullable<byte> ForeColorGreen { get; set; }
        public Nullable<byte> ForeColorBlue { get; set; }
        public Nullable<byte> BackColorRed { get; set; }
        public Nullable<byte> BackColorGreen { get; set; }
        public Nullable<byte> BackColorBlue { get; set; }
        public Nullable<int> ImageEnum { get; set; }
        public Nullable<int> ComplementImageEnum { get; set; }
        public string Formula { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public string Tooltip { get; set; }
        public string ComplementToolTip { get; set; }
    }
}
