//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLiteraturePackageFile
    {
        public int PackageFileKeyID { get; set; }
        public int FKPackageKeyID { get; set; }
        public string FileName { get; set; }
    
        public virtual tblLiteraturePackage tblLiteraturePackage { get; set; }
    }
}
