//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLVFieldDefinition2
    {
        public int FKListViewID { get; set; }
        public string FieldName { get; set; }
        public string HeaderText { get; set; }
        public Nullable<short> DefaultWidth { get; set; }
        public Nullable<byte> ColumnEditor { get; set; }
        public Nullable<bool> AllowFiltering { get; set; }
        public bool AllowSorting { get; set; }
        public Nullable<int> DefaultOperator { get; set; }
        public string DefaultCriteria { get; set; }
        public Nullable<int> SupportTableID { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsRepNumberBaseFilter { get; set; }
        public Nullable<bool> IncludeBlanksInDefaultFilter { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string LinkFieldColumn { get; set; }
        public string FilterByColumn { get; set; }
        public string SortByColumn { get; set; }
        public int GroupWiseType { get; set; }
        public Nullable<int> ValAppearance { get; set; }
        public Nullable<int> ValConditionalAction { get; set; }
        public Nullable<int> HeaderIconID { get; set; }
        public string AgeColumn { get; set; }
        public bool AgePast { get; set; }
        public bool AgeFuture { get; set; }
        public Nullable<byte> ButtonDisplayStyle { get; set; }
        public bool AllowHidding { get; set; }
        public bool Pinned { get; set; }
    }
}
