//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMSPBillingWorkTable
    {
        public int MSPBillingWorkTableKeyID { get; set; }
        public int RepNumber { get; set; }
        public string AccountName { get; set; }
        public string ProviderDescription { get; set; }
        public int AgreementNumber { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> LastBilledDate { get; set; }
        public Nullable<System.DateTime> LastPolledDate { get; set; }
        public string SalesTaxCode { get; set; }
        public int ProviderType { get; set; }
        public int AccountNumber { get; set; }
        public Nullable<System.DateTime> AgreementEndDate { get; set; }
        public Nullable<byte> BIllingPeriodMultiplier { get; set; }
        public Nullable<byte> DayToBill { get; set; }
        public Nullable<int> FkPayMethods { get; set; }
        public bool EmailInvoices { get; set; }
        public byte DayToProcessPayment { get; set; }
        public bool AllItemsAreTaxExempt { get; set; }
        public bool Consolidate { get; set; }
        public bool TreatAgreementPriceAsMonthlyTotal { get; set; }
        public Nullable<System.DateTime> NextBillingPeriod { get; set; }
    }
}
