//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMSPAgreementAssetType
    {
        public int MSPAgreementAssetTypesKeyID { get; set; }
        public int AgreementNumber { get; set; }
        public int FKMSPAssetTypes { get; set; }
        public Nullable<int> DefaultPriceLevel { get; set; }
        public Nullable<decimal> DefaultFlatPrice { get; set; }
        public bool UseFlatPriceDefault { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string ItemDescription { get; set; }
    
        public virtual tblMSPAssetType tblMSPAssetType { get; set; }
        public virtual tblMSPAgreement tblMSPAgreement { get; set; }
        public virtual tblPriceLevel tblPriceLevel { get; set; }
    }
}
