//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNonStockItemWorkTable
    {
        public int NonStockItemWorkTableKeyID { get; set; }
        public int RepNumber { get; set; }
        public int QuoteNumber { get; set; }
        public int SONumber { get; set; }
        public int LineNumber { get; set; }
        public string ItemId { get; set; }
        public string ItemDescription { get; set; }
        public string Type { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal ManufacturerListPrice { get; set; }
        public decimal Cost { get; set; }
        public bool Taxable { get; set; }
        public bool SubjectToSingleItemTax { get; set; }
        public bool SubjectToProviderTax { get; set; }
        public bool Serialized { get; set; }
        public string ItemCategory { get; set; }
        public string ItemSubCategory { get; set; }
        public string ReceivingGLCode { get; set; }
        public string IncomeGLCode { get; set; }
        public string CostGLCode { get; set; }
        public int SourceDetailKeyID { get; set; }
    }
}
