//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNetworkCarSetting
    {
        public int counter { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<long> interval { get; set; }
        public Nullable<System.DateTime> lastfleetcheck { get; set; }
        public Nullable<System.DateTime> lastgpscheck { get; set; }
    }
}
