//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpportunityStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOpportunityStage()
        {
            this.tblOpportunities = new HashSet<tblOpportunity>();
        }
    
        public int OpportunityStageKeyID { get; set; }
        public string OpportunityDescription { get; set; }
        public string ForwardActivityName { get; set; }
        public string BackwardActivityName { get; set; }
        public string OpportunityStageDescription { get; set; }
        public Nullable<decimal> ProbabilityOfSale { get; set; }
        public Nullable<short> DaysToClose { get; set; }
        public short AgeThresholdForWorkflow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOpportunity> tblOpportunities { get; set; }
    }
}
