//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhysicalInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhysicalInventory()
        {
            this.tblPhysicalInventorySerialNumbers = new HashSet<tblPhysicalInventorySerialNumber>();
        }
    
        public int PhysicalInventoryKeyID { get; set; }
        public string Location { get; set; }
        public string LocationType { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public bool Serialized { get; set; }
        public string ItemCategory { get; set; }
        public bool HotItem { get; set; }
        public decimal InventoryCost { get; set; }
        public decimal CostVariance { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public bool QuantityChanged { get; set; }
        public int QuantityAllLocations { get; set; }
        public Nullable<int> QuantityCountedAllLocations { get; set; }
        public string CostingMethod { get; set; }
        public int QuantityInSystem { get; set; }
        public Nullable<int> QuantityCounted { get; set; }
        public string ExceptionMemo { get; set; }
        public Nullable<int> Variance { get; set; }
        public string Bin { get; set; }
        public string PartNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhysicalInventorySerialNumber> tblPhysicalInventorySerialNumbers { get; set; }
    }
}
