//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectPhaseCheckListTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProjectPhaseCheckListTemplate()
        {
            this.tblProjectPhaseCheckListTemplateDetails = new HashSet<tblProjectPhaseCheckListTemplateDetail>();
        }
    
        public string ProjectPhaseCheckListName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProjectPhaseCheckListTemplateDetail> tblProjectPhaseCheckListTemplateDetails { get; set; }
    }
}
