//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPODetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPODetail()
        {
            this.tblPOAssemblyDetails = new HashSet<tblPOAssemblyDetail>();
            this.tblPOPostingJournals = new HashSet<tblPOPostingJournal>();
            this.tblPOReceipts = new HashSet<tblPOReceipt>();
            this.tblPOSerialNumbers = new HashSet<tblPOSerialNumber>();
        }
    
        public int PODetailKeyID { get; set; }
        public int PONumber { get; set; }
        public int LineNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string PartNumber { get; set; }
        public string VendorItemNumber { get; set; }
        public string UnitOfMeasure { get; set; }
        public string ReceivingLocation { get; set; }
        public double QuantityOrdered { get; set; }
        public decimal ProjectedCost { get; set; }
        public decimal TotalProjectedCost { get; set; }
        public bool RepairCostFlag { get; set; }
        public int UnitOfValue { get; set; }
        public decimal ReceivedCost { get; set; }
        public double QuantityCancelled { get; set; }
        public bool Stock { get; set; }
        public bool DistributionFlag { get; set; }
        public string Comment { get; set; }
        public string CancelledComment { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string GLCode { get; set; }
        public string CaseItemID { get; set; }
        public string CaseItemDescription { get; set; }
        public string CaseUnitOfMeasure { get; set; }
        public double DisplayQuantityOrdered { get; set; }
        public decimal CaseUnitCost { get; set; }
        public bool CaseOrder { get; set; }
        public bool UpdateBaseCostAndSellPrices { get; set; }
        public bool ClosedAssembly { get; set; }
        public string Type { get; set; }
        public bool UpdateVendorCost { get; set; }
        public string ReceivingBin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOAssemblyDetail> tblPOAssemblyDetails { get; set; }
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOPostingJournal> tblPOPostingJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOReceipt> tblPOReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOSerialNumber> tblPOSerialNumbers { get; set; }
    }
}
