//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortalModule
    {
        public int ID { get; set; }
        public string ModuleName { get; set; }
        public bool ShowModule { get; set; }
        public bool AdminOnly { get; set; }
        public Nullable<bool> Target { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ModuleLink { get; set; }
        public string Icon { get; set; }
        public int PortalRightID { get; set; }
        public string Portal { get; set; }
        public Nullable<bool> PortalEntry { get; set; }
    }
}
