//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriceLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPriceLevel()
        {
            this.tblMSPAccountAssets = new HashSet<tblMSPAccountAsset>();
            this.tblMSPAgreementAssetTypes = new HashSet<tblMSPAgreementAssetType>();
            this.tblMSPAgreementNonAssets = new HashSet<tblMSPAgreementNonAsset>();
            this.tblPriceLevelGLCodeOverrides = new HashSet<tblPriceLevelGLCodeOverride>();
            this.tblPriceLevelOverrides = new HashSet<tblPriceLevelOverride>();
            this.tblSOTemplateParts = new HashSet<tblSOTemplatePart>();
            this.tblSOTemplatePartsAssemblyDetails = new HashSet<tblSOTemplatePartsAssemblyDetail>();
        }
    
        public int PriceLevelsKeyID { get; set; }
        public Nullable<int> FkPriceLevelCategories { get; set; }
        public string Description { get; set; }
        public float Markup { get; set; }
        public float Markdown { get; set; }
        public float Margin { get; set; }
        public string IncomeGlCode { get; set; }
        public string CostGlCode { get; set; }
        public bool IsRepairLevel { get; set; }
        public byte PriceBasis { get; set; }
        public byte CostToUse { get; set; }
        public bool ApplyQuantityDiscounts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMSPAccountAsset> tblMSPAccountAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMSPAgreementAssetType> tblMSPAgreementAssetTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMSPAgreementNonAsset> tblMSPAgreementNonAssets { get; set; }
        public virtual tblPriceLevelCategory tblPriceLevelCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPriceLevelGLCodeOverride> tblPriceLevelGLCodeOverrides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPriceLevelOverride> tblPriceLevelOverrides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSOTemplatePart> tblSOTemplateParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSOTemplatePartsAssemblyDetail> tblSOTemplatePartsAssemblyDetails { get; set; }
    }
}
