//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentLog
    {
        public long PaymentLogKeyID { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public System.DateTime Date { get; set; }
        public string InvoicesPaid { get; set; }
        public Nullable<int> RepNumber { get; set; }
        public string PaymentTransactionID { get; set; }
    }
}
