//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOAssemblyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPOAssemblyDetail()
        {
            this.tblPOAssemblySerials = new HashSet<tblPOAssemblySerial>();
        }
    
        public int POAssemblyDetailKeyID { get; set; }
        public int FKPODetail { get; set; }
        public int PONumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public double Quantity { get; set; }
        public string Type { get; set; }
        public string GLCode { get; set; }
        public decimal ProjectedCostEach { get; set; }
        public decimal TotalProjectedCost { get; set; }
        public decimal ActualCost { get; set; }
    
        public virtual tblPODetail tblPODetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOAssemblySerial> tblPOAssemblySerials { get; set; }
    }
}
