//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortalSetting
    {
        public int ID { get; set; }
        public string SkinName { get; set; }
        public Nullable<int> ParentTemp { get; set; }
        public Nullable<bool> Active { get; set; }
        public string pagestyle { get; set; }
        public string pagealign { get; set; }
        public Nullable<int> formsize { get; set; }
        public string bgcolor { get; set; }
        public string bordercolor { get; set; }
        public Nullable<int> borderwidth { get; set; }
        public Nullable<bool> roundcorners { get; set; }
        public string bgimage { get; set; }
        public string maintablecolor { get; set; }
        public string font { get; set; }
        public string fontcolor { get; set; }
        public string fontsize { get; set; }
        public string linkcolor { get; set; }
        public string hlinkcolor { get; set; }
        public string alinkcolor { get; set; }
        public string vlinkcolor { get; set; }
        public string linkstyle { get; set; }
        public string headercolor { get; set; }
        public string headerbg { get; set; }
        public string buttoncolor { get; set; }
        public string buttonbg { get; set; }
        public string navstyle { get; set; }
        public string ShowIcons { get; set; }
        public string navbgcolor { get; set; }
        public string navhoverbgcolor { get; set; }
        public string navlinkcolor { get; set; }
        public string navhoverlinkcolor { get; set; }
        public string navborder { get; set; }
        public string image_home { get; set; }
        public string image_header { get; set; }
        public string image_logo { get; set; }
        public string logochoice { get; set; }
        public string TabTheme { get; set; }
        public string GridTheme { get; set; }
    }
}
