//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortalControl
    {
        public int PortalControlID { get; set; }
        public string ControlName { get; set; }
        public Nullable<System.Guid> ControlID { get; set; }
        public string ControlTitle { get; set; }
        public int PortalRightID { get; set; }
        public string Zone { get; set; }
        public Nullable<int> Order { get; set; }
        public string Portal { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
