//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortalPermission
    {
        public int PortalPermissionsID { get; set; }
        public int PortalRoleID { get; set; }
        public int PortalRightID { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
