//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortalOption
    {
        public int PortalOptionsID { get; set; }
        public string SOTakenBy { get; set; }
        public string SOTechAssigned { get; set; }
        public string SOStatus { get; set; }
        public string SOType { get; set; }
        public string SOPriority { get; set; }
        public string SavePath { get; set; }
        public string NetPath { get; set; }
        public string EMailFrom { get; set; }
        public string EmailCC { get; set; }
        public string MailServer { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Port { get; set; }
        public string DateFormat { get; set; }
        public string LoginMessage { get; set; }
        public string AccessDeniedMesssage { get; set; }
        public string QuoteDisclaimer { get; set; }
        public string LeadFormConfirmEmail { get; set; }
        public string PrivacyPolicy { get; set; }
        public string QuoteTY { get; set; }
        public string ContactUsTY { get; set; }
        public string ServiceTY { get; set; }
        public string DateInfo { get; set; }
        public Nullable<int> JournalRepNumber { get; set; }
        public Nullable<bool> Logins { get; set; }
        public Nullable<bool> DocumentPrinting { get; set; }
        public Nullable<bool> ContactRequests { get; set; }
        public Nullable<bool> QuoteRequests { get; set; }
        public Nullable<bool> ProfileUpdate { get; set; }
        public Nullable<bool> PasswordChange { get; set; }
        public Nullable<bool> SORequests { get; set; }
        public Nullable<bool> CreateOpportunityOnQuoteRequest { get; set; }
        public string Name { get; set; }
        public string LeadSource { get; set; }
        public string OpportunityType { get; set; }
        public string OpportunityStatus { get; set; }
        public string QuoteSavePath { get; set; }
        public string QuoteNetPath { get; set; }
        public string AcceptedStatus { get; set; }
        public string DeniedStatus { get; set; }
        public bool PrintProposal { get; set; }
        public bool PrintTotalsOnlyNotLineItems { get; set; }
        public bool PrintLineItemPrices { get; set; }
        public bool PrintAssemblyDetail { get; set; }
        public bool PrintAssemblyDetailPrices { get; set; }
        public bool PrintMFGListPrice { get; set; }
        public bool AllowCustomerUpdate { get; set; }
        public bool CreateSONote { get; set; }
        public bool UpdateWorkRequested { get; set; }
        public bool UpdateWorkPerformed { get; set; }
        public bool ShowSOTimeLogs { get; set; }
        public bool ShowSOParts { get; set; }
        public bool ShowSOPartsGrid { get; set; }
        public bool ShowSOItems { get; set; }
        public string ShowSOPricing { get; set; }
        public bool ShowSONotes { get; set; }
        public string SONoteTopic { get; set; }
        public bool ShowWorkPerformed_RequestDetails { get; set; }
        public bool ShowSOItemsServiced { get; set; }
        public bool ShowInvoicedQuotes { get; set; }
        public bool ShowQuotesConvertedToWO { get; set; }
        public bool ShowQuotesConvertedToSO { get; set; }
        public bool AllowUserToOverridePriority { get; set; }
        public bool ShowSONotesPrint { get; set; }
        public bool ShowSOTimeLogsPrint { get; set; }
        public bool leadstoqueue { get; set; }
        public bool leadstotigerpaw { get; set; }
        public string AccountType { get; set; }
        public string AccountStatus { get; set; }
        public string HotNote { get; set; }
        public string AccountRep { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool ShowWorkRequested { get; set; }
        public bool ShowWorkPerformed { get; set; }
        public bool ShowPostedInvoice { get; set; }
        public bool ShowApprovedInvoice { get; set; }
        public bool ShowOpenInvoice { get; set; }
        public bool AllowPayments { get; set; }
        public bool EmailErrors { get; set; }
        public string ErrorEmail { get; set; }
        public int SOLimit { get; set; }
        public int QuoteLimit { get; set; }
        public int InvoiceLimit { get; set; }
        public int ProjectLimit { get; set; }
        public int ContractLimit { get; set; }
        public bool OpenService { get; set; }
        public bool OpenQuotes { get; set; }
        public bool OpenProjects { get; set; }
        public bool OpenInvoices { get; set; }
        public bool OpenContracts { get; set; }
        public string ExcludeSOType { get; set; }
        public string ExcludeQuoteType { get; set; }
        public bool AllowNewContact { get; set; }
        public bool CreateLoginNewContact { get; set; }
        public int LoginDefaultRole { get; set; }
        public bool UseContractPriority { get; set; }
        public bool AllowDispute { get; set; }
        public bool StopPaymentOnDispute { get; set; }
        public bool ShowSOStatus { get; set; }
        public bool OverideSOStatus { get; set; }
        public bool ShowSOPriority { get; set; }
        public bool ShowTechAssigned { get; set; }
        public bool UseSOContractSelection { get; set; }
    }
}
