//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseOrder()
        {
            this.tblPODetails = new HashSet<tblPODetail>();
        }
    
        public int PoNumber { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string ConfirmedTo { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public bool PrintedFlag { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> BuyerNumber { get; set; }
        public string Comments { get; set; }
        public string OrderTerms { get; set; }
        public string FreightTerms { get; set; }
        public string ShippingMethod { get; set; }
        public bool UpdateLatestCost { get; set; }
        public bool AllowBackorders { get; set; }
        public int LinesOnOrder { get; set; }
        public double ProjectedItems { get; set; }
        public decimal ProjectedCost { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string DefaultReceivingLocation { get; set; }
        public string DefaultCostLevel { get; set; }
        public string InvoiceNumber { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhone { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string InvoiceTerms { get; set; }
        public decimal Freight { get; set; }
        public bool BlindShip { get; set; }
        public string TrackingNumber { get; set; }
        public int RequestedByRep { get; set; }
        public int AccountNumber { get; set; }
        public int QuoteNumber { get; set; }
        public int SONumber { get; set; }
        public bool PaidInFull { get; set; }
        public string InternalComments { get; set; }
        public int VendorAccountNumber { get; set; }
        public bool PoWasAddedToBatch { get; set; }
        public int ProjectNumber { get; set; }
        public string Shipper { get; set; }
        public string DefaultReceivingBin { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblInvoiceTerm tblInvoiceTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPODetail> tblPODetails { get; set; }
        public virtual tblRep tblRep { get; set; }
    }
}
