//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfessionalServicesBillingWizardWorkTable
    {
        public int ProfessionalServicesBillingWizardWorkTableKeyID { get; set; }
        public int RepNumber { get; set; }
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public int SoNumber { get; set; }
        public int InvoiceRepNumber { get; set; }
        public Nullable<int> ProjectKeyId { get; set; }
        public string SalesTaxCode { get; set; }
        public float SalesTaxRate { get; set; }
        public string ARCustomerNumber { get; set; }
        public string BillCompanyName { get; set; }
        public string InvoiceTerms { get; set; }
        public int QuoteNumber { get; set; }
        public string FreightTerms { get; set; }
        public string ShipVia { get; set; }
        public string ShipCompanyName { get; set; }
        public string LogText { get; set; }
        public int InvoiceNumber { get; set; }
        public string BriefDescription { get; set; }
        public bool GSTIsTaxable { get; set; }
        public int FKPayMethods { get; set; }
    }
}
