//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhoneNumber
    {
        public int PhoneNumbersKeyID { get; set; }
        public string RawPhoneNumber { get; set; }
        public string FormattedPhoneNumber { get; set; }
        public int AccountNumber { get; set; }
        public int ContactNumber { get; set; }
        public string PhoneLocation { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public bool PrimaryIndicator { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
    }
}
