//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOReceipt
    {
        public int POReceiptsKeyID { get; set; }
        public int PONumber { get; set; }
        public int FKPODetail { get; set; }
        public double QuantityReceived { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public int ReceivedBy { get; set; }
        public string Shipper { get; set; }
        public string ShipperTrackingNumber { get; set; }
        public bool Posted { get; set; }
        public string Location { get; set; }
        public string ItemID { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string Bin { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblPODetail tblPODetail { get; set; }
    }
}
