//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuote()
        {
            this.tblQuoteNotes = new HashSet<tblQuoteNote>();
            this.tblQuoteTemplates = new HashSet<tblQuoteTemplate>();
        }
    
        public int QuoteNumber { get; set; }
        public string QuoteDescription { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public int AccountNumber { get; set; }
        public int ContactNumber { get; set; }
        public string ContactPhone { get; set; }
        public int RepNumber { get; set; }
        public string QuoteComments { get; set; }
        public Nullable<System.DateTime> QuoteExpirationDate { get; set; }
        public string Job { get; set; }
        public string Type { get; set; }
        public string Terms { get; set; }
        public string QuoteSource { get; set; }
        public int NextDetailSequenceNumber { get; set; }
        public bool InUseFlag { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int VoidedBy { get; set; }
        public decimal TotalManufacturerListPrice { get; set; }
        public decimal TotalBookPrice { get; set; }
        public int PriceLevel { get; set; }
        public decimal TotalNetSell { get; set; }
        public decimal TotalGrossSell { get; set; }
        public decimal DiscountAmount { get; set; }
        public float DiscountPercent { get; set; }
        public double DiscountMarginPercent { get; set; }
        public decimal DiscountSellForPrice { get; set; }
        public decimal TotalDollarsDiscounted { get; set; }
        public float TotalPercentDiscounted { get; set; }
        public decimal TotalNetInvoice { get; set; }
        public decimal LaborNet { get; set; }
        public decimal MaterialNet { get; set; }
        public decimal Freight { get; set; }
        public decimal TradeIn { get; set; }
        public decimal Credit { get; set; }
        public decimal Deposit { get; set; }
        public Nullable<int> TotalCOD { get; set; }
        public decimal AmountDue { get; set; }
        public string TotalRemark { get; set; }
        public decimal Cost { get; set; }
        public decimal MaterialCost { get; set; }
        public decimal LaborCost { get; set; }
        public float Margin { get; set; }
        public decimal Profit { get; set; }
        public decimal Fat { get; set; }
        public float CommissionPercent { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal AmcCommissionPercent { get; set; }
        public decimal AmcCommissionAmount { get; set; }
        public int Lines { get; set; }
        public string StagingLocation { get; set; }
        public Nullable<int> SalesStageValue { get; set; }
        public float ProbabilityOfClose { get; set; }
        public string ProbabilityOfCloseNote { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> EstimatedCloseDate { get; set; }
        public bool Approved { get; set; }
        public int ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public bool ApprovedForInvoicing { get; set; }
        public bool ShowInForecasts { get; set; }
        public double HoursNeeded { get; set; }
        public double HoursEntered { get; set; }
        public string CustomerPurchaseOrder { get; set; }
        public string SalesTaxCode { get; set; }
        public float TaxPercent { get; set; }
        public bool FreightTaxable { get; set; }
        public bool TaxLabor { get; set; }
        public bool Taxable { get; set; }
        public decimal TaxableAmount { get; set; }
        public decimal Tax { get; set; }
        public bool GSTExempt { get; set; }
        public decimal GSTaxableAmount { get; set; }
        public decimal GSTax { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public int WorkorderNumber { get; set; }
        public string WorkorderStatus { get; set; }
        public Nullable<System.DateTime> WorkorderDate { get; set; }
        public bool WorkOrderClosed { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public int SONumber { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> PaidInFullDate { get; set; }
        public string PaymentMethod { get; set; }
        public string BillingComments { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string Shipper { get; set; }
        public string PackagingComments { get; set; }
        public string AirbillNumber { get; set; }
        public string ShippingMethod { get; set; }
        public string ShippingInstructions { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhone { get; set; }
        public string ShipContactName { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string BillContactName { get; set; }
        public bool PrintTotalsOnlyNotLineItems { get; set; }
        public bool PrintLineItemPrices { get; set; }
        public bool PrintAssemblyDetail { get; set; }
        public bool PrintAssemblyDetailPrices { get; set; }
        public bool PrintMFGListPrice { get; set; }
        public string InternalComments { get; set; }
        public int PONumber { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
        public int FKOpportunityKeyID { get; set; }
        public int BillToAccountNumber { get; set; }
        public bool GSTIsTaxable { get; set; }
        public Nullable<int> ProjectKeyID { get; set; }
        public Nullable<int> ProjectPhaseKeyID { get; set; }
        public bool PrintLeaseInfo { get; set; }
        public double LeaseRate { get; set; }
        public int LeaseMonths { get; set; }
        public string LeaseBuyout { get; set; }
        public decimal LeasePayment { get; set; }
        public string ProgressiveInvoiceTotalComment { get; set; }
        public decimal ProviderTaxableAmount { get; set; }
        public decimal ProviderTax { get; set; }
        public float ProviderTaxRAte { get; set; }
        public bool TaxComputedBeforeTradeIn { get; set; }
        public bool GSTaxComputedBeforeTradeIn { get; set; }
        public float GSTaxRate { get; set; }
        public string BillToARCustomerNumber { get; set; }
        public bool CompletelyServiceOrdered { get; set; }
        public Nullable<System.DateTime> DateToInstall { get; set; }
        public Nullable<decimal> LeaseDown { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public bool PaymentFromGreatAmerica { get; set; }
        public string RateCardName { get; set; }
        public bool ChangesMadeAfterPaymentFromGreatAmerica { get; set; }
        public bool CanDiscountedItemsGetQuoteDiscount { get; set; }
        public bool IsChangeOrder { get; set; }
        public short InternalExternalChangeOrder { get; set; }
        public bool DisplayOnPortal { get; set; }
        public int FKPayMethods { get; set; }
        public string StagingBin { get; set; }
        public Nullable<double> PercentagePoints { get; set; }
        public string MaintenanceType { get; set; }
        public string MaintenanceAmount { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblPaymentMethod tblPaymentMethod { get; set; }
        public virtual tblQuoteDescription tblQuoteDescription { get; set; }
        public virtual tblQuoteJob tblQuoteJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuoteNote> tblQuoteNotes { get; set; }
        public virtual tblQuoteSource tblQuoteSource { get; set; }
        public virtual tblQuoteStatus tblQuoteStatus { get; set; }
        public virtual tblQuoteType tblQuoteType { get; set; }
        public virtual tblWorkOrderStatus tblWorkOrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuoteTemplate> tblQuoteTemplates { get; set; }
    }
}
