//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuickSale
    {
        public int QuickSaleNumber { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public string Terms { get; set; }
        public Nullable<int> SalesRep { get; set; }
        public Nullable<decimal> TotalGrossSell { get; set; }
        public Nullable<decimal> TotalDollarsDiscounted { get; set; }
        public Nullable<float> TotalPercentDiscounted { get; set; }
        public Nullable<decimal> TotalNetSell { get; set; }
        public string SalesTaxCode { get; set; }
        public Nullable<float> SalesTaxPercent { get; set; }
        public Nullable<bool> FreightTaxable { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GSTaxableAmount { get; set; }
        public Nullable<decimal> GSTax { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> TotalNetInvoice { get; set; }
        public Nullable<decimal> TotalAmountDue { get; set; }
        public string ShipFromLocation { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhone { get; set; }
        public string ShipContactName { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string BillContactName { get; set; }
        public string BillingStyle { get; set; }
        public string PONumber { get; set; }
        public string ARCustomerNumber { get; set; }
        public string AccountingCompanyID { get; set; }
        public string BOTaxCode { get; set; }
        public string BOTaxType { get; set; }
        public Nullable<bool> GSTIsTaxable { get; set; }
        public Nullable<decimal> TotalCostOnSourceDocument { get; set; }
        public Nullable<decimal> ProviderTaxableAmount { get; set; }
        public Nullable<decimal> ProviderTax { get; set; }
        public Nullable<float> ProviderTaxRate { get; set; }
        public Nullable<decimal> TotalProviderTaxCredited { get; set; }
        public Nullable<decimal> TotalGSTaxCredited { get; set; }
        public Nullable<float> GSTaxRate { get; set; }
        public bool ReleaseQuantitiesOnDelete { get; set; }
        public float DiscountPercent { get; set; }
        public int FKPayMethods { get; set; }
    }
}
