//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuoteToSOCrossReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuoteToSOCrossReference()
        {
            this.tblQuoteToSODetails = new HashSet<tblQuoteToSODetail>();
        }
    
        public int QuoteToSOCrossReferenceKeyID { get; set; }
        public int QuoteNumber { get; set; }
        public int SONumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuoteToSODetail> tblQuoteToSODetails { get; set; }
    }
}
