//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRep()
        {
            this.tblBackTracks = new HashSet<tblBackTrack>();
            this.tblGridSettings = new HashSet<tblGridSetting>();
            this.tblGridSettings2 = new HashSet<tblGridSettings2>();
            this.tblItemMovements = new HashSet<tblItemMovement>();
            this.tblJournals = new HashSet<tblJournal>();
            this.tblPalmSyncs = new HashSet<tblPalmSync>();
            this.tblPurchaseOrders = new HashSet<tblPurchaseOrder>();
            this.tblAssignedRepGroups = new HashSet<tblAssignedRepGroup>();
            this.tblRepExpertises = new HashSet<tblRepExpertise>();
            this.tblReportsRepFavorites = new HashSet<tblReportsRepFavorite>();
            this.tblRepsInfoes = new HashSet<tblRepsInfo>();
            this.tblRepSOPrintSettings = new HashSet<tblRepSOPrintSetting>();
            this.tblSOLogs = new HashSet<tblSOLog>();
            this.tblSONotes = new HashSet<tblSONote>();
            this.tblSYSSerializations = new HashSet<tblSYSSerialization>();
            this.tblTimeSlips = new HashSet<tblTimeSlip>();
            this.tblUserConnections = new HashSet<tblUserConnection>();
            this.tblViewDefinitionRepSettings = new HashSet<tblViewDefinitionRepSetting>();
            this.tblViewLayoutRepShares = new HashSet<tblViewLayoutRepShare>();
            this.tblViewRepLayoutSettings = new HashSet<tblViewRepLayoutSetting>();
            this.tblWorkFlowEventStaticRecipients = new HashSet<tblWorkFlowEventStaticRecipient>();
            this.tblSecurityGroups = new HashSet<tblSecurityGroup>();
        }
    
        public int RepNumber { get; set; }
        public int PersonalAccountNumber { get; set; }
        public bool Inactive { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string RepName { get; set; }
        public string Title { get; set; }
        public string NameOnLetter { get; set; }
        public string SignatureBlock { get; set; }
        public string SignatureGraphic { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string PagerPhone { get; set; }
        public string FaxPhone { get; set; }
        public string OfficePhone { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateEmployed { get; set; }
        public string Department { get; set; }
        public string PassWord { get; set; }
        public string Status { get; set; }
        public bool RepIsPublic { get; set; }
        public int UserLevel { get; set; }
        public string Territory { get; set; }
        public string SkillLevel { get; set; }
        public decimal HourlyRate { get; set; }
        public string ReportsTo { get; set; }
        public decimal Quota { get; set; }
        public float Commission { get; set; }
        public string AccountingLinkSalesRepID { get; set; }
        public string DefaultCity { get; set; }
        public string DefaultState { get; set; }
        public string DefaultCountry { get; set; }
        public string DefaultAccountType { get; set; }
        public int DefaultSnooze { get; set; }
        public string WordTemplate { get; set; }
        public string DefaultTemplateDir { get; set; }
        public string FaxPrefix { get; set; }
        public string FaxFromAreaCode { get; set; }
        public string FacSysServerName { get; set; }
        public string FacSysUserName { get; set; }
        public string FacSysPassword { get; set; }
        public bool ShowTooltips { get; set; }
        public bool CreateLabelFile { get; set; }
        public bool CloseSOHistOnShow { get; set; }
        public bool CheckConflicts { get; set; }
        public bool TasktoNote { get; set; }
        public bool DefaultAlarm { get; set; }
        public bool StartMaximized { get; set; }
        public bool ShowLastServiceOrderOnLogin { get; set; }
        public bool ShowLastQuoteOnLogin { get; set; }
        public string LastDocumentPath { get; set; }
        public string DefaultDocumentType { get; set; }
        public bool DefaultLogintoPursuit { get; set; }
        public bool DefaultLogintoService { get; set; }
        public bool DefaultLogintoQuotes { get; set; }
        public bool DefaultLogintoParts { get; set; }
        public int ShowViewOnLogin { get; set; }
        public bool ShowPriceBookSelectOnItemID { get; set; }
        public bool PromptOnApplicationClose { get; set; }
        public bool SpellingCheckSpelling { get; set; }
        public bool SpellingLoadCache { get; set; }
        public bool SpellingIgnoreWithNumbers { get; set; }
        public bool SpellingIgnoreUpperCase { get; set; }
        public bool SpellingIgnoreMixedCase { get; set; }
        public string SpellingCustomDictionary { get; set; }
        public int ReminderQuantity { get; set; }
        public int ReminderInterval { get; set; }
        public bool SendMailUsingOutlook { get; set; }
        public int CheckRemindersInterval { get; set; }
        public float CalendarTopTime { get; set; }
        public string ReportsPath { get; set; }
        public bool UseQuoteTemplates { get; set; }
        public bool ClearPreviousConnections { get; set; }
        public int WorkFlowCacheTime { get; set; }
        public bool PrintSpecialInstructions { get; set; }
        public bool PrintItemsServiced { get; set; }
        public bool PrintPartsLaborUsedWithPrices { get; set; }
        public bool PrintPartsLaborUsedWithoutPrices { get; set; }
        public bool PrintPartsLaborUsedSerialNumbers { get; set; }
        public bool PrintTimeLogRecords { get; set; }
        public bool PrintServiceOrderNotes { get; set; }
        public bool PrintAssemblyDetailRecords { get; set; }
        public bool PrintContractInformation { get; set; }
        public string SyncInventoryLocation { get; set; }
        public bool AccountsCanBeReassigned { get; set; }
        public string AccountViewContactGridSettings { get; set; }
        public Nullable<System.DateTime> ChangedPasswordDate { get; set; }
        public string NTLoginName { get; set; }
        public bool FastPriceBookSearch { get; set; }
        public string DefaultSearchFieldOnPriceBookSelect { get; set; }
        public bool LookupCityStateByZip { get; set; }
        public int DefaultReminderQuantity { get; set; }
        public int DefaultReminderInterval { get; set; }
        public bool DontRestoreJournalListFilterSettings { get; set; }
        public bool CanHotSyncPursuit { get; set; }
        public bool CanHotSyncService { get; set; }
        public bool AlwaysLogEmailsToJournal { get; set; }
        public bool ShowTipsOnStartup { get; set; }
        public bool AlwaysShowOutlookSendDialogBox { get; set; }
        public bool EnlargePopupsForBigScreens { get; set; }
        public bool CanAccessIVR { get; set; }
        public bool ReturnToFiltersOnListViews { get; set; }
        public bool CanAccessWebInterface { get; set; }
        public bool SOPrintSpecialInstructions { get; set; }
        public bool SOPrintServiceOrderNotes { get; set; }
        public bool SOPrintPartsLaborWithPrices { get; set; }
        public bool SOPrintPartsLaborWithoutPrices { get; set; }
        public bool SOPrintTimeLogs { get; set; }
        public bool SOPrintContractInformation { get; set; }
        public string PBSearchForText { get; set; }
        public string PBSearchInField { get; set; }
        public string PBFilterBy { get; set; }
        public string PBShowWhat { get; set; }
        public int PBPriceLevel { get; set; }
        public bool PBRememberSettings { get; set; }
        public bool PBHideInactiveItems { get; set; }
        public int TigerpawInterfaceStyle { get; set; }
        public bool RetainLogTech { get; set; }
        public bool RetainLogComment { get; set; }
        public bool RetainLogReason { get; set; }
        public bool RetainLogStartDate { get; set; }
        public bool RetainLogStartTime { get; set; }
        public bool RetainLogEndDate { get; set; }
        public bool RetainLogEndTime { get; set; }
        public bool UseLogStartDateAsEndDate { get; set; }
        public int CalendarViewPrimeColor { get; set; }
        public int CalendarViewNonPrimeColor { get; set; }
        public string DefaultWarehouse { get; set; }
        public string VehicleID { get; set; }
        public Nullable<bool> DefaultEmailToHTML { get; set; }
        public string HomePhoneExt { get; set; }
        public string MobilePhoneExt { get; set; }
        public string PagerPhoneExt { get; set; }
        public string FaxPhoneExt { get; set; }
        public string OfficePhoneExt { get; set; }
        public string PBItemSubCategory { get; set; }
        public string PBItemCategory { get; set; }
        public string PBItemType { get; set; }
        public string CheckSum { get; set; }
        public short BatchTimeEntryStartUpMode { get; set; }
        public bool ShowOnlyActiveContractsInGrid { get; set; }
        public int CalendarViewTimeInterval { get; set; }
        public int GroupCalendarViewZoomLevel { get; set; }
        public int ProjectViewTimelineZoom { get; set; }
        public float BillablePercent { get; set; }
        public bool CustomerPortalAdmin { get; set; }
        public string CorelyticsUserID { get; set; }
        public string CorelyticsPassword { get; set; }
        public string WindowsUserName { get; set; }
        public bool IsCoManagedITTech { get; set; }
        public bool CMITCanEscalate { get; set; }
        public bool CMITCanViewOtherRepsTasks { get; set; }
        public bool CMITCanViewJournal { get; set; }
        public bool UseSearchWildcard { get; set; }
        public bool CMITCanViewAllTicketsForAccount { get; set; }
        public bool CMITCanViewParts { get; set; }
        public bool CMITCanModifyParts { get; set; }
        public bool CMITCanViewItemsServiced { get; set; }
        public bool CMITCanModifyItemsServiced { get; set; }
        public string PasswordMS { get; set; }
        public bool ForcePasswordChange { get; set; }
        public Nullable<System.DateTime> LastReadNewsDate { get; set; }
        public bool DefaultLogintoSales { get; set; }
        public Nullable<System.DateTime> PrimaryEmailConfirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBackTrack> tblBackTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGridSetting> tblGridSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGridSettings2> tblGridSettings2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemMovement> tblItemMovements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJournal> tblJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPalmSync> tblPalmSyncs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseOrder> tblPurchaseOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignedRepGroup> tblAssignedRepGroups { get; set; }
        public virtual tblRepsApiUserInfo tblRepsApiUserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRepExpertise> tblRepExpertises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReportsRepFavorite> tblReportsRepFavorites { get; set; }
        public virtual tblVehicle tblVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRepsInfo> tblRepsInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRepSOPrintSetting> tblRepSOPrintSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSOLog> tblSOLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSONote> tblSONotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSYSSerialization> tblSYSSerializations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTimeSlip> tblTimeSlips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserConnection> tblUserConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewDefinitionRepSetting> tblViewDefinitionRepSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewLayoutRepShare> tblViewLayoutRepShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewRepLayoutSetting> tblViewRepLayoutSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkFlowEventStaticRecipient> tblWorkFlowEventStaticRecipients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSecurityGroup> tblSecurityGroups { get; set; }
    }
}
