//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int ReportID { get; set; }
        public string ReportTitle { get; set; }
        public string ReportFileName { get; set; }
        public string ReportDescription { get; set; }
        public string WHEREClause { get; set; }
        public bool SystemEntry { get; set; }
        public bool SystemAdministratorOnly { get; set; }
        public int UsageCount { get; set; }
    }
}
