//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRMADetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRMADetail()
        {
            this.tblRMAReceipts = new HashSet<tblRMAReceipt>();
            this.tblRMASerialNumbers = new HashSet<tblRMASerialNumber>();
        }
    
        public int RMADetailKeyID { get; set; }
        public int FKRMA { get; set; }
        public string RMANumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string PONumber { get; set; }
        public decimal ItemCost { get; set; }
        public System.DateTime DatePlacedOnRMA { get; set; }
        public int Quantity { get; set; }
        public int QuantityFilled { get; set; }
        public int QuantityReceived { get; set; }
        public int QuantityCancelled { get; set; }
        public int SONumber { get; set; }
        public int FKExchange { get; set; }
        public Nullable<System.DateTime> ToVendorShipDate { get; set; }
        public Nullable<System.DateTime> ToVendorShipTime { get; set; }
        public string ToVendorShipMethod { get; set; }
        public string ToVendorTrackingNumber { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> ExpectedTime { get; set; }
        public string ExpectedShipMethod { get; set; }
        public decimal VendorReimbursementAmount { get; set; }
        public Nullable<System.DateTime> ReimbursementDate { get; set; }
        public string Status { get; set; }
        public short ItemSource { get; set; }
        public int BinLocation { get; set; }
        public int AccountNumber { get; set; }
        public string CustomerRMANumber { get; set; }
        public Nullable<System.DateTime> ReceivedFromCustomerDate { get; set; }
        public string ShipMethodFromCustomer { get; set; }
        public int ContractNumber { get; set; }
        public int FKCustomerInventory { get; set; }
        public int FKCustomerInventoryAssemblyDetail { get; set; }
        public string Comments { get; set; }
        public string GLCode { get; set; }
        public bool Serialized { get; set; }
        public string Type { get; set; }
        public int QuantityReturnedToStockOrCustomer { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
        public int CancelledBy { get; set; }
        public decimal ReplacementCostDifferential { get; set; }
        public string ReplacementGLCode { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public bool DropShipFlag { get; set; }
        public string ShipToName { get; set; }
        public string ShipToAddress1 { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToState { get; set; }
        public string ShipToPostalCode { get; set; }
        public string ShipToCountry { get; set; }
    
        public virtual tblRMA tblRMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRMAReceipt> tblRMAReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRMASerialNumber> tblRMASerialNumbers { get; set; }
    }
}
