//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRepSOPrintSetting
    {
        public int RepNumber { get; set; }
        public string CustomFormToUse { get; set; }
        public bool PrintItemsServicedPackList { get; set; }
        public bool PrintPartsUsedPackList { get; set; }
        public bool PrintStandardSO { get; set; }
        public bool PrintNotes { get; set; }
        public bool PrintItemsServiced { get; set; }
        public bool PrintPartsUsedWithPrices { get; set; }
        public bool PrintPartsUsedWithoutPrices { get; set; }
        public bool PrintTimeLogs { get; set; }
        public bool PrintItemsServicedPackingList { get; set; }
        public bool PrintPartsUsedPackingList { get; set; }
        public bool PackingListOnly { get; set; }
        public bool PickTicketOnly { get; set; }
    
        public virtual tblRep tblRep { get; set; }
    }
}
