//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSOTechsAssigned
    {
        public int ID { get; set; }
        public int SONumber { get; set; }
        public int RepNumber { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public bool PrimaryIndicator { get; set; }
    }
}
