//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysAddonStatu
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Machine { get; set; }
        public bool Running { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
