//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSystem()
        {
            this.tblServiceOrders = new HashSet<tblServiceOrder>();
            this.tblAccountSystems = new HashSet<tblAccountSystem>();
        }
    
        public string SystemDescription { get; set; }
        public int TechSkillLevel { get; set; }
        public string Skill { get; set; }
        public string Comments { get; set; }
        public string SystemType { get; set; }
        public string RepGroupForSystem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceOrder> tblServiceOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountSystem> tblAccountSystems { get; set; }
        public virtual tblSystemType tblSystemType { get; set; }
    }
}
