//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesTaxDollar
    {
        public int SalesTaxDollarsKeyID { get; set; }
        public string DocumentType { get; set; }
        public int DocumentNumber { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string State { get; set; }
        public string SalesTaxCode { get; set; }
        public string SalesTaxDistrict { get; set; }
        public float TaxRate { get; set; }
        public decimal TaxOnLabor { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal TaxableAmount { get; set; }
        public decimal TaxableLaborAmount { get; set; }
        public decimal SalesTax { get; set; }
        public decimal GSTaxableAmount { get; set; }
        public decimal GSTax { get; set; }
        public decimal ProviderTaxableAmount { get; set; }
        public decimal ProviderTax { get; set; }
        public decimal DistrictTaxableAmount { get; set; }
        public decimal GrossSales { get; set; }
        public decimal TaxableMaterialsAmount { get; set; }
        public decimal NonTaxableMaterialsAmount { get; set; }
        public decimal NonTaxableLaborAmount { get; set; }
    }
}
