//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubcontractorInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSubcontractorInformation()
        {
            this.tblSubcontractorExpertises = new HashSet<tblSubcontractorExpertise>();
            this.tblSubcontractorServiceZones = new HashSet<tblSubcontractorServiceZone>();
            this.tblSubContractorSystems = new HashSet<tblSubContractorSystem>();
        }
    
        public int AccountNumber { get; set; }
        public string InsuranceCertificateNumber { get; set; }
        public Nullable<System.DateTime> InsuranceCertificateExpirationDate { get; set; }
        public string LicenseState { get; set; }
        public string LicenseNumber { get; set; }
        public int NumberOfTechs { get; set; }
        public decimal LaborRate { get; set; }
        public decimal MaterialsMarkUpPercent { get; set; }
        public string Comments { get; set; }
        public bool MasterAgreementIndicator { get; set; }
        public decimal TripCharge { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubcontractorExpertise> tblSubcontractorExpertises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubcontractorServiceZone> tblSubcontractorServiceZones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubContractorSystem> tblSubContractorSystems { get; set; }
    }
}
