//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSYSSerialization
    {
        public int RepNumber { get; set; }
        public string TabHeaderXML { get; set; }
        public string TabOrderXML { get; set; }
    
        public virtual tblRep tblRep { get; set; }
    }
}
