//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSOTemplateLog
    {
        public int SOTemplateLogsKeyID { get; set; }
        public int FKSOTemplates { get; set; }
        public string LogReason { get; set; }
        public short WhichRep { get; set; }
        public int RepNumber { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public int TimeOffset { get; set; }
        public short OffsetInterval { get; set; }
        public string Comments { get; set; }
        public int LogHours { get; set; }
        public short LogMinutes { get; set; }
    
        public virtual tblLogReason tblLogReason { get; set; }
        public virtual tblSOTemplate tblSOTemplate { get; set; }
    }
}
