//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSearchTemplate
    {
        public string SearchCategory { get; set; }
        public string SearchTemplateName { get; set; }
        public string StoredProcedureName { get; set; }
        public bool DefaultforCategory { get; set; }
        public int ModuleID { get; set; }
    
        public virtual tblSearchCategory tblSearchCategory { get; set; }
    }
}
