//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysReportSetting
    {
        public int SysReportSettingsKeyID { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string ReportsPath { get; set; }
        public bool LogoOnLeft { get; set; }
        public bool InvoiceCommentsAtEnd { get; set; }
        public bool A4Paper { get; set; }
        public bool ReportUsageCounter { get; set; }
    }
}
