//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSYSExchangeTask_Deletes
    {
        public int RepNumber { get; set; }
        public int TaskKeyID { get; set; }
        public Nullable<bool> isAppointment { get; set; }
        public System.DateTime DateTaskDeleted { get; set; }
        public string ItemID { get; set; }
    }
}
