//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSOLogsBilled
    {
        public int SOLogsBilledKeyID { get; set; }
        public int FKSOPartsUsed { get; set; }
        public int FKSOLogs { get; set; }
        public double HoursConverted { get; set; }
        public System.DateTime DateConverted { get; set; }
        public int ByRep { get; set; }
    }
}
