//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysComputerSetting
    {
        public string ComputerName { get; set; }
        public int RepNumber { get; set; }
        public string TWAINDriver { get; set; }
        public bool UseTWAINInterface { get; set; }
        public int DialOutMethod { get; set; }
        public int COMMPort { get; set; }
        public bool PulseDial { get; set; }
        public string BaudRate { get; set; }
        public string TAPILineName { get; set; }
        public int LastTigerpawStyle { get; set; }
    }
}
