//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeverity
    {
        public int SeverityID { get; set; }
        public string FKSLASeverity { get; set; }
        public string FKPriority { get; set; }
        public int Rank { get; set; }
        public Nullable<int> ReceivedToOpen { get; set; }
        public Nullable<bool> ReceivedToOpen24x7 { get; set; }
        public Nullable<int> OpenToClose { get; set; }
        public Nullable<bool> OpenToClose24x7 { get; set; }
        public Nullable<int> ReceivedToClose { get; set; }
        public Nullable<bool> ReceivedToClose24x7 { get; set; }
        public Nullable<int> RequestToOpen { get; set; }
        public Nullable<bool> RequestToOpen24x7 { get; set; }
    
        public virtual tblPriorities2 tblPriorities2 { get; set; }
        public virtual tblSLASeverity tblSLASeverity { get; set; }
    }
}
