//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduledActivity
    {
        public int ScheduledActivitiesKeyID { get; set; }
        public int AccountNumber { get; set; }
        public int ContactNumber { get; set; }
        public Nullable<int> PathNumber { get; set; }
        public Nullable<int> StepNumber { get; set; }
        public string ActivityName { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string SpecialInstructions { get; set; }
        public int ResponsibleEmployee { get; set; }
        public int ScheduledBy { get; set; }
        public int CompletedBy { get; set; }
        public bool TaskFlag { get; set; }
        public int TaskDays { get; set; }
        public string TaskTime { get; set; }
        public int TaskRep { get; set; }
        public int EmailOnBehalfOfRep { get; set; }
        public int MergeSignedByRep { get; set; }
        public int PathSequence { get; set; }
        public int SONumber { get; set; }
        public int QuoteNumber { get; set; }
        public bool ProcessingError { get; set; }
        public int ProcessingBatch { get; set; }
        public int ActivityID { get; set; }
    
        public virtual tblActivity tblActivity { get; set; }
    }
}
