//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeSlip
    {
        public int TimeSlipKeyID { get; set; }
        public int Tech { get; set; }
        public string TimeLogReason { get; set; }
        public string LogComment { get; set; }
        public int LogHours { get; set; }
        public int LogMinutes { get; set; }
        public int ElapsedHours { get; set; }
        public int ElapsedMinutes { get; set; }
        public bool Billable { get; set; }
        public float Mileage { get; set; }
        public decimal Fuel { get; set; }
        public decimal Parking { get; set; }
        public decimal Tolls { get; set; }
        public decimal Meals { get; set; }
        public decimal Accomodations { get; set; }
        public decimal MiscExpenses { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public decimal LogReasonLaborRate { get; set; }
        public int RateType { get; set; }
        public int RateBasis { get; set; }
        public Nullable<decimal> TotalExpenses { get; set; }
        public string RejectedStatusReason { get; set; }
        public int AcceptOrRejectedBy { get; set; }
        public byte AcceptanceStatus { get; set; }
        public int DeductHours { get; set; }
        public short DeductMinutes { get; set; }
        public int UtilizationHours { get; set; }
        public short UtilizationMinutes { get; set; }
        public bool CreditUtilizationTime { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string InternalComments { get; set; }
    
        public virtual tblLogReason tblLogReason { get; set; }
        public virtual tblRep tblRep { get; set; }
    }
}
