//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxWatch
    {
        public int TaxWatchID { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> WatchType { get; set; }
    }
}
