//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateImportPartsAssembly
    {
        public int AssyDetailKey { get; set; }
        public int TemplateKey { get; set; }
        public int PartsKey { get; set; }
        public int Sequence { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public decimal Quantity { get; set; }
        public short PricingMethod { get; set; }
        public decimal FixedPrice { get; set; }
        public string Type { get; set; }
        public string Memo { get; set; }
        public bool PrintOnInvoice { get; set; }
    
        public virtual tblTemplateImportPart tblTemplateImportPart { get; set; }
    }
}
