//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskActionPlanDetail
    {
        public int TaskActionPlanDetailKeyID { get; set; }
        public int FKTaskActionPlans { get; set; }
        public int StepNumber { get; set; }
        public string Subject { get; set; }
        public string Location { get; set; }
        public string TaskType { get; set; }
        public string TaskAction { get; set; }
        public string Priority { get; set; }
        public string TaskComment { get; set; }
        public string ResourceName { get; set; }
        public int Duration { get; set; }
        public string DurationInterval { get; set; }
        public int RepOnTask { get; set; }
        public int WhichTask { get; set; }
        public int PreviousTaskOffset { get; set; }
        public string OffsetInterval { get; set; }
        public int RepNumber { get; set; }
        public string RepGroup { get; set; }
        public Nullable<System.DateTime> SpecificStartTime { get; set; }
    
        public virtual tblTaskActionPlan tblTaskActionPlan { get; set; }
        public virtual tblTaskAction tblTaskAction { get; set; }
    }
}
