//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransferDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTransferDetail()
        {
            this.tblTransferSerialNumbers = new HashSet<tblTransferSerialNumber>();
        }
    
        public int TransferDetailKeyID { get; set; }
        public int TransferNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public int Quantity { get; set; }
        public bool Serialized { get; set; }
        public int QuantitySerialsSelected { get; set; }
    
        public virtual tblPriceBook tblPriceBook { get; set; }
        public virtual tblTransfer tblTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransferSerialNumber> tblTransferSerialNumbers { get; set; }
    }
}
