//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViewLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblViewLayout()
        {
            this.tblViewLayoutAdvancedFilterItems = new HashSet<tblViewLayoutAdvancedFilterItem>();
            this.tblViewLayoutColumns = new HashSet<tblViewLayoutColumn>();
            this.tblViewLayoutRepShares = new HashSet<tblViewLayoutRepShare>();
            this.tblViewRepLayoutSettings = new HashSet<tblViewRepLayoutSetting>();
        }
    
        public long PKLayoutID { get; set; }
        public long FKViewID { get; set; }
        public string LayoutName { get; set; }
        public bool IsSystem { get; set; }
        public string SelectedFont { get; set; }
        public Nullable<long> PrimaryBandColor { get; set; }
        public Nullable<long> ChildBandColor { get; set; }
        public byte[] FilterXml { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> LastModifiedByRep { get; set; }
    
        public virtual tblViewDefinition tblViewDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewLayoutAdvancedFilterItem> tblViewLayoutAdvancedFilterItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewLayoutColumn> tblViewLayoutColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewLayoutRepShare> tblViewLayoutRepShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewRepLayoutSetting> tblViewRepLayoutSettings { get; set; }
    }
}
