//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViewLayoutColumn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblViewLayoutColumn()
        {
            this.tblViewLayoutColumnFilters = new HashSet<tblViewLayoutColumnFilter>();
        }
    
        public long PKLayoutColumnID { get; set; }
        public long FKLayoutID { get; set; }
        public long FKTableColumnID { get; set; }
        public Nullable<bool> IsCustomColumn { get; set; }
        public bool IsPrimaryBand { get; set; }
        public bool IsVisible { get; set; }
        public int SummaryType { get; set; }
        public Nullable<int> ColumnPosition { get; set; }
        public Nullable<int> GroupByOrdinal { get; set; }
        public Nullable<int> OrderByOrdinal { get; set; }
    
        public virtual tblViewLayout tblViewLayout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewLayoutColumnFilter> tblViewLayoutColumnFilters { get; set; }
    }
}
