//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblViewLayoutAdvancedFilterItem
    {
        public long PKLayoutSelectedItemsID { get; set; }
        public long FKLayoutID { get; set; }
        public string AccountGroupItems { get; set; }
        public string AccountProfileItems { get; set; }
        public string ContactGroupItems { get; set; }
        public string ContactProfileItems { get; set; }
        public string SICCodeItems { get; set; }
        public string SOProfileItems { get; set; }
        public string ItemIDItems { get; set; }
        public string FilterClause { get; set; }
        public string SortClauseXML { get; set; }
        public string ColumnWidthXML { get; set; }
        public string GroupingColumnXML { get; set; }
    
        public virtual tblViewLayout tblViewLayout { get; set; }
    }
}
