//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkFlowEventType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkFlowEventType()
        {
            this.tblWorkflowEventAssignedDocumentTypes = new HashSet<tblWorkflowEventAssignedDocumentType>();
            this.tblWorkFlowEventDefinitions = new HashSet<tblWorkFlowEventDefinition>();
        }
    
        public int WorkFlowEventsTypeID { get; set; }
        public string EventType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkflowEventAssignedDocumentType> tblWorkflowEventAssignedDocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkFlowEventDefinition> tblWorkFlowEventDefinitions { get; set; }
    }
}
