//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkFlowEventConditionDataSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkFlowEventConditionDataSource()
        {
            this.tblWorkFlowEventConditionDocumentTypeDataSources = new HashSet<tblWorkFlowEventConditionDocumentTypeDataSource>();
            this.tblWorkFlowEventConditionFields = new HashSet<tblWorkFlowEventConditionField>();
        }
    
        public int WorkflowEventConditionDataSourcesKeyID { get; set; }
        public string DataSourceName { get; set; }
        public string DataSourceDescription { get; set; }
        public string KeyFieldName { get; set; }
        public string KeyFieldDataType { get; set; }
        public string WorkflowQueueFieldName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkFlowEventConditionDocumentTypeDataSource> tblWorkFlowEventConditionDocumentTypeDataSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkFlowEventConditionField> tblWorkFlowEventConditionFields { get; set; }
    }
}
