//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkflowEventConditionSelectedField
    {
        public int WorkflowEventConditionSelectedFieldsKeyID { get; set; }
        public int FKWorkflowEventDefinitions { get; set; }
        public int FKWorkflowEventConditionFields { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public int KeyValue { get; set; }
        public string ControlType { get; set; }
        public string RawPhoneNumber { get; set; }
    
        public virtual tblWorkFlowEventDefinition tblWorkFlowEventDefinition { get; set; }
    }
}
