//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_MSPAccountAssets
    {
        public int MSPAccountAssetsKeyID { get; set; }
        public int AccountNumber { get; set; }
        public int ProviderType { get; set; }
        public string ProvidersAssetID { get; set; }
        public int FKMSPAssetTypes { get; set; }
        public Nullable<int> PriceLevel { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool UseFlatPrice { get; set; }
        public string ExternalID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> LastPolledDate { get; set; }
        public string PriceLevelDescription { get; set; }
        public string AssetType { get; set; }
        public string ProviderDescription { get; set; }
        public string DeviceURL { get; set; }
        public string ProvidersAssetName { get; set; }
        public int FKAssignedExternalAccount { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public bool InActiveIndicator { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string OS { get; set; }
        public string SerialNumber { get; set; }
        public string Description { get; set; }
        public string LastLoggedInUser { get; set; }
    }
}
