//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_cf_Weblink_Customer_Login
    {
        public int ContactNumber { get; set; }
        public string ContactName { get; set; }
        public string Customer_Web_Login { get; set; }
        public string Customer_Web_Password { get; set; }
    }
}
