//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Activities
    {
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string ActivityName { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public int ScheduledActivitiesKeyID { get; set; }
        public string SpecialInstructions { get; set; }
        public string TaskComment { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string CompanyName { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string RepAliasFirstName { get; set; }
        public string RepAliasMiddleInitial { get; set; }
        public string RepAliasLastName { get; set; }
    }
}
