//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_cf_Migrated_Contact_Fields
    {
        public int ContactNumber { get; set; }
        public string ContactName { get; set; }
        public string clblUserFFText1_C1 { get; set; }
        public string clblUserFFText2_C2 { get; set; }
        public string clblUserFFText3_C3 { get; set; }
        public string clblUserFFText4_C4 { get; set; }
        public string clblUserFFText5_C5 { get; set; }
        public string clblUserFFText6_C6 { get; set; }
        public string clblUserFFText7_C7 { get; set; }
        public string clblUserFFText8_C8 { get; set; }
        public string clblUserPopup1_C9 { get; set; }
        public string clblUserPopup2_C10 { get; set; }
        public string clblUserPopup3_C11 { get; set; }
        public string clblUserDate1_C12 { get; set; }
        public string clblUserDate2_C13 { get; set; }
        public string clblUserDate3_C14 { get; set; }
        public string clblUserDate4_C15 { get; set; }
        public string clblUserNum1_C16 { get; set; }
        public string clblUserNum2_C17 { get; set; }
        public string clblUserMoney1_C18 { get; set; }
        public string clblUserMoney2_C19 { get; set; }
    }
}
