//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_AccountContactsAndNotesList
    {
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string ContactName { get; set; }
        public int ContactNumber { get; set; }
        public string AccountType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string HotNote { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string PrimaryFaxNumberFormatted { get; set; }
        public string RepName { get; set; }
        public string AccountStatus { get; set; }
        public string Title { get; set; }
        public string RepPhone { get; set; }
        public string RepFax { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public string AccountID { get; set; }
        public string Note { get; set; }
        public string AccountSource { get; set; }
        public int RepNumber { get; set; }
        public string AccountGroup { get; set; }
    }
}
