//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_EmailAnalyticsActivities
    {
        public string PathName { get; set; }
        public string PathDescription { get; set; }
        public string ActivityName { get; set; }
        public int Step { get; set; }
        public Nullable<int> PathNumber { get; set; }
        public int ActivityID { get; set; }
        public Nullable<System.DateTime> LaunchDate { get; set; }
        public Nullable<System.DateTime> LastResponse { get; set; }
    }
}
