//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Portal_Invoices_Employee
    {
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string SONumber { get; set; }
        public string QuoteNumber { get; set; }
        public string WorkOrderNumber { get; set; }
        public int ContractNumber { get; set; }
        public string Status { get; set; }
        public string Terms { get; set; }
        public decimal TotalAmountDue { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> NetDays { get; set; }
        public int SalesRep { get; set; }
        public int RepNumber { get; set; }
        public string SO { get; set; }
        public string SourceDocument { get; set; }
        public Nullable<System.DateTime> DateEmailed { get; set; }
        public Nullable<System.DateTime> DatepaymentWasProcessed { get; set; }
        public string RepName { get; set; }
        public Nullable<System.DateTime> FirstPrintDate { get; set; }
        public Nullable<System.DateTime> FirstEmailDate { get; set; }
    }
}
