//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_PriceBook
    {
        public string PartNumber { get; set; }
        public string ItemDescription { get; set; }
        public string Type { get; set; }
        public string ItemCategory { get; set; }
        public bool Taxable { get; set; }
        public string Bin { get; set; }
        public decimal BaseCost { get; set; }
        public decimal AverageCost { get; set; }
        public string ItemID { get; set; }
        public bool HotItem { get; set; }
        public string Features { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public int QuantityOnHand { get; set; }
        public int QuantityReserved { get; set; }
        public int QuantityOnOrder { get; set; }
        public int MinimumQuantity { get; set; }
        public decimal ManufacturerListPrice { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string CaseItemID { get; set; }
    }
}
