//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_CustomerInventory
    {
        public int CustomerInventoryKeyID { get; set; }
        public int CustomerInventoryAssemblyDetailKeyID { get; set; }
        public int AccountNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<System.DateTime> WarrantyExpiry { get; set; }
        public Nullable<System.DateTime> MFGWarrantyExpiry { get; set; }
        public string Status { get; set; }
        public string StatusComment { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.DateTime> LastPMDate { get; set; }
        public Nullable<System.DateTime> NextPMDate { get; set; }
        public int ContractNumber { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DatePurchasedFromVendor { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public Nullable<System.DateTime> NextActionDate { get; set; }
        public string NextActionType { get; set; }
    }
}
