//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_InvoiceListView
    {
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> SourceDocument { get; set; }
        public string SourceDocumentType { get; set; }
        public int SONumber { get; set; }
        public int QuoteNumber { get; set; }
        public int WorkOrderNumber { get; set; }
        public int MSPAgreementNumber { get; set; }
        public int ContractNumber { get; set; }
        public Nullable<int> ProjectKeyID { get; set; }
        public string PONumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> StatusBy { get; set; }
        public bool OnHold { get; set; }
        public bool Printed { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public int FKAltBillTo { get; set; }
        public int FKAltShipTo { get; set; }
        public string Terms { get; set; }
        public string FreightTerms { get; set; }
        public string Reference { get; set; }
        public int SalesRep { get; set; }
        public Nullable<decimal> TotalGrossSell { get; set; }
        public Nullable<decimal> TotalDollarsDiscounted { get; set; }
        public Nullable<decimal> TotalPercentDiscounted { get; set; }
        public Nullable<decimal> TotalNetSell { get; set; }
        public string SalesTaxCode { get; set; }
        public float SalesTaxPercent { get; set; }
        public bool FreightTaxable { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GSTaxableAmount { get; set; }
        public Nullable<decimal> GSTax { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> TotalNetInvoice { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> TotalAmountDue { get; set; }
        public string TotalComment { get; set; }
        public bool PartialInvoice { get; set; }
        public string ShipFromLocation { get; set; }
        public string Shipper { get; set; }
        public string ShipVia { get; set; }
        public Nullable<System.DateTime> BilledFrom { get; set; }
        public Nullable<System.DateTime> BilledThru { get; set; }
        public string ExternalInvoiceNumber { get; set; }
        public string VoidReason { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhone { get; set; }
        public string ShipContactName { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string BillContactName { get; set; }
        public string BillingStyle { get; set; }
        public bool PrintPackingSlipWithInvoice { get; set; }
        public bool PrintCompanyHeader { get; set; }
        public bool PrintContractIncludesData { get; set; }
        public bool PrintContractSpecialInstructions { get; set; }
        public string Comments { get; set; }
        public int BatchNumber { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public string ARCustomerNumber { get; set; }
        public string AccountingCompanyID { get; set; }
        public string ARReference { get; set; }
        public Nullable<System.DateTime> ARDate { get; set; }
        public string GLReference { get; set; }
        public Nullable<System.DateTime> GLDate { get; set; }
        public string CostingMethodUsed { get; set; }
        public bool ARFeedWasActive { get; set; }
        public bool GLFeedWasActive { get; set; }
        public Nullable<decimal> TotalPriceCredited { get; set; }
        public Nullable<decimal> TotalTaxCredited { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public string BOTaxCode { get; set; }
        public string BOTaxType { get; set; }
        public Nullable<decimal> BOTaxCredit { get; set; }
        public Nullable<decimal> BOTax { get; set; }
        public Nullable<decimal> AppliedTradein { get; set; }
        public Nullable<decimal> AppliedGSTradein { get; set; }
        public Nullable<decimal> AppliedBOTradein { get; set; }
        public Nullable<decimal> PrepaidContractAmount { get; set; }
        public bool SendPrepaidAmountsToAR { get; set; }
        public string PostingExceptionMemo { get; set; }
        public string ContractInvoiceType { get; set; }
        public string InternalComments { get; set; }
        public short VersionNumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> OnHoldDate { get; set; }
        public int OnHoldRep { get; set; }
        public bool GSTIsTaxable { get; set; }
        public Nullable<decimal> TotalCostOnSourceDocument { get; set; }
        public Nullable<decimal> PostedCost { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> DiscountAllowed { get; set; }
        public bool IsProgressiveInvoice { get; set; }
        public bool IsFinalProgressiveInvoice { get; set; }
        public float ProgressiveBillingPercent { get; set; }
        public float ProgressiveCostPercent { get; set; }
        public bool CreateRevenueJournalEntries { get; set; }
        public bool CreateCostJournalEntries { get; set; }
        public string ProgressiveInvoiceRevenueGLCode { get; set; }
        public string ProgressiveInvoiceCostGLCode { get; set; }
        public Nullable<decimal> ProviderTaxableAmount { get; set; }
        public Nullable<decimal> ProviderTax { get; set; }
        public float ProviderTaxRate { get; set; }
        public Nullable<decimal> TotalProviderTaxCredited { get; set; }
        public Nullable<decimal> TotalGSTaxCredited { get; set; }
        public Nullable<decimal> TotalFreightCredited { get; set; }
        public bool IsConsolidatedInvoice { get; set; }
        public int ConsolidatedInvoiceNumber { get; set; }
        public string Prefix { get; set; }
        public bool TaxComputedBeforeTradeIn { get; set; }
        public bool GSTaxComputedBeforeTradeIn { get; set; }
        public float GSTaxRate { get; set; }
        public string RepName { get; set; }
        public Nullable<bool> CreditFlag { get; set; }
        public string AccountID { get; set; }
        public Nullable<int> RepsRepNumber { get; set; }
        public bool CompanyHideGSTaxRelatedInformation { get; set; }
        public Nullable<bool> CompanyHideProviderTaxRelatedInformation { get; set; }
        public float SysCompanyProviderTaxRate { get; set; }
        public string PrintItemorPartNum { get; set; }
        public string ConsolidatedInvoiceDisclaimer { get; set; }
        public bool InvoiceCommentsAtEnd { get; set; }
    }
}
