//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_ContactsInfo
    {
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string AccountAddress1 { get; set; }
        public string AccountAddress2 { get; set; }
        public string AccountCity { get; set; }
        public string AccountHoteNote { get; set; }
        public string AccountPostalCode { get; set; }
        public string AccountState { get; set; }
        public int ContactNumber { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string ContactDepartment { get; set; }
        public string ContactAddress1 { get; set; }
        public string ContactAddress2 { get; set; }
        public string ContactState { get; set; }
        public string ContactCity { get; set; }
        public string ContactPostalCode { get; set; }
        public string ContactPersonalNotes { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> PrimaryContactNumber { get; set; }
        public string CompleteAddress { get; set; }
        public Nullable<int> AccountRepNumber { get; set; }
    }
}
