//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVARPayments
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string ReceiptReference { get; set; }
        public decimal ReceiptAmount { get; set; }
        public string Payor { get; set; }
        public string Service { get; set; }
        public string PaymentTransactionID { get; set; }
        public int ARReceipts_PendingKeyID { get; set; }
        public int ID { get; set; }
        public Nullable<int> Age { get; set; }
        public string PayMethodName { get; set; }
    }
}
