//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_HPLVServiceOrders
    {
        public int ID { get; set; }
        public int SONumber { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string AccountName { get; set; }
        public string ContactName { get; set; }
        public string BriefDescription { get; set; }
        public string GeneralSymptoms { get; set; }
        public string SOType { get; set; }
        public int AccountNumber { get; set; }
        public int RepNumber { get; set; }
        public Nullable<int> SOStatusRank { get; set; }
        public Nullable<int> SOPriorityRank { get; set; }
    }
}
