//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_PriceLevels
    {
        public Nullable<int> PriceLevel { get; set; }
        public int PriceOverride { get; set; }
        public Nullable<bool> GlCodeOverride { get; set; }
        public string ItemId { get; set; }
        public Nullable<int> PriceLevelCategoriesKeyID { get; set; }
        public string PriceLevelCategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<float> Markup { get; set; }
        public Nullable<float> Markdown { get; set; }
        public Nullable<float> Margin { get; set; }
        public Nullable<decimal> FlatPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string IncomeGlCode { get; set; }
        public string CostGlCode { get; set; }
        public Nullable<bool> IsRepairLevel { get; set; }
        public Nullable<byte> PriceBasis { get; set; }
        public Nullable<byte> CostToUse { get; set; }
        public string CostToUseDescription { get; set; }
        public bool ApplyQuantityDiscounts { get; set; }
    }
}
