//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVOpportunities
    {
        public int ID { get; set; }
        public int OpportunityKeyID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Age { get; set; }
        public Nullable<int> TaskStatusImage { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public Nullable<System.DateTime> EstimatedCloseDate { get; set; }
        public Nullable<decimal> ExpectedAmount { get; set; }
        public string OpportunityName { get; set; }
        public string AccountName { get; set; }
        public string CurrentStage { get; set; }
        public int OpportunityOwner { get; set; }
        public string OwnerName { get; set; }
        public string OpportunityStatus { get; set; }
        public string TicketState { get; set; }
        public Nullable<int> StateOfOpportunity { get; set; }
        public string NextStep { get; set; }
        public string OpportunityType { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CloseReason { get; set; }
        public string OpportunitySource { get; set; }
        public int AccountNumber { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PhoneNumberFormatted { get; set; }
        public string Strategy { get; set; }
        public string OpportunityNotes { get; set; }
        public System.DateTime LastModified { get; set; }
        public int LastModifiedByRep { get; set; }
        public string LastModifiedByRepName { get; set; }
        public Nullable<decimal> BestCaseAmount { get; set; }
        public Nullable<decimal> WorstCaseAmount { get; set; }
        public Nullable<int> ProbabilityPercent { get; set; }
        public string Competition { get; set; }
        public int NumberOfTasks { get; set; }
        public string NumberOfEmployees { get; set; }
        public Nullable<bool> QuotePresent { get; set; }
        public string HowDidYouHearAboutUs { get; set; }
        public decimal FinalQuoteAmount { get; set; }
        public Nullable<int> LeadScore { get; set; }
        public string AccountType { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<int> eAccountGroup { get; set; }
        public Nullable<int> eAccountProfile { get; set; }
        public Nullable<int> eSICCode { get; set; }
        public Nullable<int> eContactGroup { get; set; }
    }
}
