//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Portal_QuoteAssemblyDetails_Employee
    {
        public int QuoteAssemblyDetailKeyID { get; set; }
        public int FKQuoteDetail { get; set; }
        public int QuoteNumber { get; set; }
        public string AssemblyItemID { get; set; }
        public string ItemID { get; set; }
        public double Quantity { get; set; }
        public decimal ManufacturerListPrice { get; set; }
        public string ItemDescription { get; set; }
        public decimal BookPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal TotalSellingPrice { get; set; }
        public bool PrintOnQuote { get; set; }
        public bool PrintOnInvoice { get; set; }
        public double QuantityOrdered { get; set; }
        public Nullable<System.DateTime> OrderByDate { get; set; }
        public bool UseThisCostWhenOrdering { get; set; }
        public decimal Cost { get; set; }
        public int AccountNumber { get; set; }
    }
}
