//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_PurchaseOrders
    {
        public int PoNumber { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string ContactName { get; set; }
        public string ContactFirstName { get; set; }
        public string RepName { get; set; }
        public string RepEmail { get; set; }
        public string RepOfficePhone { get; set; }
        public string RepEmailSignatureText { get; set; }
        public string RepEmailSignatureHTML { get; set; }
        public string ConfirmedTo { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string OrderTerms { get; set; }
        public string FreightTerms { get; set; }
        public string ShippingMethod { get; set; }
        public decimal ProjectedCost { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string ShipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhone { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string InvoiceTerms { get; set; }
    }
}
