//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVInvoices
    {
        public int ID { get; set; }
        public Nullable<int> Image { get; set; }
        public bool InDispute { get; set; }
        public Nullable<int> InDisputeImage { get; set; }
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Status { get; set; }
        public string ContractType { get; set; }
        public Nullable<bool> Paid { get; set; }
        public bool PaymentPending { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountRepNum { get; set; }
        public string AccountRepName { get; set; }
        public int AccountNumber { get; set; }
        public string ContractBillingDescription { get; set; }
        public Nullable<decimal> TotalGrossSell { get; set; }
        public Nullable<decimal> TotalDollarsDiscounted { get; set; }
        public Nullable<decimal> TotalNetSell { get; set; }
        public Nullable<decimal> TotalNetInvoice { get; set; }
        public Nullable<decimal> TotalAmountDue { get; set; }
        public Nullable<decimal> TotalPayments { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public string AccountID { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> SourceDocument { get; set; }
        public string ARCustomerNumber { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public Nullable<int> WorkOrderNumber { get; set; }
        public int SalesRep { get; set; }
        public string RepName { get; set; }
        public Nullable<bool> CreditFlag { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int BatchNumber { get; set; }
        public string SalesTaxCode { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GSTax { get; set; }
        public Nullable<decimal> ProviderTax { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public string PostingExceptionMemo { get; set; }
        public Nullable<int> ConsolidatedInvoiceNumber { get; set; }
        public bool OnHold { get; set; }
        public bool Printed { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<System.DateTime> FirstPrintDate { get; set; }
        public Nullable<int> SentToAccounting { get; set; }
        public string Reference { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public int Age { get; set; }
        public string ContractInvoiceType { get; set; }
        public int SONumber { get; set; }
        public int ContractNumber { get; set; }
        public Nullable<int> ProjectKeyID { get; set; }
        public int MSPAgreementNumber { get; set; }
        public bool IsConsolidatedInvoice { get; set; }
        public Nullable<int> eAccountGroup { get; set; }
        public Nullable<int> eAccountProfile { get; set; }
        public Nullable<int> eItemID { get; set; }
        public Nullable<System.DateTime> DateEmailed { get; set; }
        public Nullable<System.DateTime> FirstEmailDate { get; set; }
        public string ContractDescription { get; set; }
        public Nullable<System.DateTime> BilledFrom { get; set; }
        public Nullable<System.DateTime> BilledThru { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool DisplayOnPortal { get; set; }
        public string ARAccountNumber { get; set; }
        public string ARDepartment { get; set; }
        public bool IsCentralBillingInvoice { get; set; }
    }
}
