//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_Projects
    {
        public int ProjectNumber { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string AccountName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> EstimatedCompletionDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ApprovedBudgetAmount { get; set; }
        public Nullable<decimal> ApprovedHours { get; set; }
        public string RepName { get; set; }
        public string RepOfficePhone { get; set; }
        public string RepEmailSignatureText { get; set; }
        public string RepEmailSignatureHTML { get; set; }
        public string RepEmail1 { get; set; }
    }
}
