//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Portal_LogReasons
    {
        public decimal StandardRate { get; set; }
        public bool OvertimeIndicator { get; set; }
        public bool PremiumTimeIndicator { get; set; }
        public int RoundingToNearestMinutes { get; set; }
        public int MinimumMinutes { get; set; }
        public Nullable<int> LaborRateCategoryKeyID { get; set; }
        public string LaborRateCategory { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> FlatFee { get; set; }
        public Nullable<int> TypeRegRate { get; set; }
        public Nullable<decimal> RegularRateFixed { get; set; }
        public string RegularRatePBItemID { get; set; }
        public Nullable<int> TypeOTRate { get; set; }
        public Nullable<decimal> OvertimeRateFixed { get; set; }
        public Nullable<decimal> OvertimeRateMultiplier { get; set; }
        public string OvertimePBItemID { get; set; }
        public Nullable<int> TypePremRate { get; set; }
        public Nullable<decimal> PremiumRateFixed { get; set; }
        public Nullable<decimal> PremiumRateMultiplier { get; set; }
        public string PremiumRatePBItemID { get; set; }
        public string FlatFeePBItemID { get; set; }
        public int FKLaborRateCategory { get; set; }
        public string LogReason { get; set; }
        public string LaborItemID { get; set; }
        public bool Chargable { get; set; }
        public bool Billable { get; set; }
        public bool DoNotCopyToWorkPerformed { get; set; }
        public bool CreditUtilizationTime { get; set; }
    }
}
