//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_MSPAssetTypeXRef
    {
        public int MSPAssetTypesKeyID { get; set; }
        public int ProviderType { get; set; }
        public string AssetType { get; set; }
        public string ProviderAssetType { get; set; }
        public int FKMSPAssetTypes { get; set; }
        public string SpecialItemID { get; set; }
        public Nullable<int> DefaultPriceLevel { get; set; }
        public decimal DefaultFlatPrice { get; set; }
        public bool UseFlatPriceDefault { get; set; }
    }
}
