//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_ConsolidatedInvoiceTotals
    {
        public int ConsolidatedInvoiceNumber { get; set; }
        public Nullable<decimal> TotalGrossSell { get; set; }
        public Nullable<decimal> TotalDollarsDiscounted { get; set; }
        public Nullable<decimal> TotalNetSell { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> GSTaxableAmount { get; set; }
        public Nullable<decimal> GSTax { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> TotalNetInvoice { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> TotalAmountDue { get; set; }
        public Nullable<decimal> TotalPriceCredited { get; set; }
        public Nullable<decimal> TotalTaxCredited { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public Nullable<decimal> BOTaxCredit { get; set; }
        public Nullable<decimal> BOTax { get; set; }
        public Nullable<decimal> AppliedTradein { get; set; }
        public Nullable<decimal> AppliedBOTradein { get; set; }
        public Nullable<decimal> AppliedGSTradein { get; set; }
        public Nullable<decimal> PrepaidContractAmount { get; set; }
        public Nullable<decimal> TotalCostOnSourceDocument { get; set; }
        public Nullable<decimal> PostedCost { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> DiscountAllowed { get; set; }
        public Nullable<decimal> ProviderTaxableAmount { get; set; }
        public Nullable<decimal> ProviderTax { get; set; }
        public Nullable<decimal> TotalProviderTaxCredited { get; set; }
        public Nullable<decimal> TotalGSTaxCredited { get; set; }
        public Nullable<decimal> TotalFreightCredited { get; set; }
    }
}
