//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Tasks
    {
        public int AccountNumber { get; set; }
        public string ContactName { get; set; }
        public int ContactNumber { get; set; }
        public string ContactPrimaryPhoneFormatted { get; set; }
        public string ContactTitle { get; set; }
        public string FormattedPhoneNumber { get; set; }
        public string PPhoneLocation { get; set; }
        public string PriorityText { get; set; }
        public string RepGroup { get; set; }
        public string RepName { get; set; }
        public int ScheduledForRepNumber { get; set; }
        public Nullable<int> ServiceOrdersSONumber { get; set; }
        public string SOAccountPhone { get; set; }
        public string SOContactPhone { get; set; }
        public string SOContactPhoneLocation { get; set; }
        public string TaskAction { get; set; }
        public string TaskComment { get; set; }
        public bool TaskCompletedIndicator { get; set; }
        public Nullable<System.DateTime> TaskEndTime { get; set; }
        public int TaskKeyID { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskStartTime { get; set; }
        public int TaskSONumber { get; set; }
        public string SOContactName { get; set; }
    }
}
