//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_Quotes
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountAddr1 { get; set; }
        public string AccountAddr2 { get; set; }
        public string AccountCity { get; set; }
        public string AccountState { get; set; }
        public string AccountZip { get; set; }
        public int AccountRepNumber { get; set; }
        public int AccountPrimaryContactNumber { get; set; }
        public string AccountPrimaryEmailAddress { get; set; }
        public int QuoteNumber { get; set; }
        public string QuoteDescription { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public string QuoteContactPhone { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactFullName { get; set; }
        public string ContactEmailAddress { get; set; }
        public string ContactLetterSalutation { get; set; }
        public string AcctRepFirstName { get; set; }
        public string AcctRepLastName { get; set; }
        public string AcctRepFullName { get; set; }
        public string AcctRepTitle { get; set; }
        public string AcctRepAddr1 { get; set; }
        public string AcctRepAddr2 { get; set; }
        public string AcctRepCity { get; set; }
        public string AcctRepState { get; set; }
        public string AcctRepPostalCode { get; set; }
        public string AcctRepOfficePhone { get; set; }
        public string AcctRepEmail { get; set; }
        public string AcctRepEmailSignatureText { get; set; }
        public string AcctRepEmailSignatureHTML { get; set; }
        public string QuoteRepFirstName { get; set; }
        public string QuoteRepLastName { get; set; }
        public string QuoteRepFullName { get; set; }
        public string QuoteRepTitle { get; set; }
        public string QuoteRepAddr1 { get; set; }
        public string QuoteRepAddr2 { get; set; }
        public string QuoteRepCity { get; set; }
        public string QuoteRepState { get; set; }
        public string QuoteRepPostalCode { get; set; }
        public string QuoteRepOfficePhone { get; set; }
        public string QuoteRepEmail { get; set; }
        public string QuoteRepEmailSignatureText { get; set; }
        public string QuoteRepEmailSignatureHTML { get; set; }
        public int WorkorderNumber { get; set; }
        public string WorkorderStatus { get; set; }
        public Nullable<System.DateTime> WorkorderDate { get; set; }
        public string SONumber { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public int PONumber { get; set; }
        public string CustomerPurchaseOrder { get; set; }
        public Nullable<System.DateTime> QuoteExpirationDate { get; set; }
        public string Terms { get; set; }
        public decimal TotalManufacturerListPrice { get; set; }
        public decimal TotalNetSell { get; set; }
        public decimal TotalGrossSell { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TotalDollarsDiscounted { get; set; }
        public float TotalPercentDiscounted { get; set; }
        public decimal TotalNetInvoice { get; set; }
        public decimal Freight { get; set; }
        public decimal TradeIn { get; set; }
        public decimal Credit { get; set; }
        public decimal Deposit { get; set; }
        public decimal AmountDue { get; set; }
        public decimal Tax { get; set; }
        public string PaymentMethod { get; set; }
        public double LeaseRate { get; set; }
        public int LeaseMonths { get; set; }
        public string LeaseBuyout { get; set; }
        public string LeasePayment { get; set; }
        public decimal LeasePayment2 { get; set; }
    }
}
