//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVDebitMemos
    {
        public int DebitMemoNumber { get; set; }
        public string RMANumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> VendorAccountNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string Status { get; set; }
        public bool PrintedFlag { get; set; }
        public decimal TotalCreditAmount { get; set; }
        public string Reference { get; set; }
        public string InternalComments { get; set; }
        public int PONumber { get; set; }
        public string RepName { get; set; }
        public bool Hidden { get; set; }
        public int ID { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public int EnteredBy { get; set; }
        public Nullable<int> RMAKeyID { get; set; }
    }
}
