//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_ProjectListview
    {
        public int ProjectKeyID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int ProjectOwner { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public Nullable<decimal> BudgetWarningThreshold { get; set; }
        public Nullable<decimal> ApprovedBudgetAmount { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public Nullable<byte> OrdinalPosition { get; set; }
        public Nullable<System.DateTime> EstimatedCompletionDate { get; set; }
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string RepName { get; set; }
        public string ContactName { get; set; }
    }
}
