//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVScheduledActivities
    {
        public Nullable<System.DateTime> DueDate { get; set; }
        public string PathName { get; set; }
        public Nullable<int> StepNumber { get; set; }
        public string ActivityName { get; set; }
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string ContactName { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<bool> SendEMail { get; set; }
        public bool TaskFlag { get; set; }
        public int CreateMerge { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string ScheduledByRep { get; set; }
        public int ScheduledBy { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string CompletedByRep { get; set; }
        public Nullable<int> SONumber { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public int ScheduledActivitiesKeyID { get; set; }
        public int ID { get; set; }
        public int CompletedBy { get; set; }
        public int ContactNumber { get; set; }
        public Nullable<int> PathNumber { get; set; }
        public int PathSequence { get; set; }
    }
}
