//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LV_Portal_RMAs
    {
        public int AccountNumber { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string OriginalSerialNumber { get; set; }
        public string ReceivedSerialNumber { get; set; }
    }
}
