//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_AccountsWOOpportunities
    {
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string AccountType { get; set; }
        public int OpportunityKeyID { get; set; }
        public string OpportunityStatus { get; set; }
        public string RepRepName { get; set; }
        public string RepStatus { get; set; }
        public Nullable<int> TasksScheduledForRepNumber { get; set; }
        public Nullable<bool> TaskCompletedIndicator { get; set; }
        public Nullable<System.DateTime> ScheduledActivitiesCompleteDate { get; set; }
        public Nullable<int> ScheduledActivitiesPathNumber { get; set; }
        public int AccountsRepNumber { get; set; }
        public Nullable<int> RepRepNumber { get; set; }
    }
}
