//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Quotes
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string AccountAddr1 { get; set; }
        public string AccountAddr2 { get; set; }
        public string AccountCity { get; set; }
        public string AccountState { get; set; }
        public string AccountZip { get; set; }
        public int AccountRepNumber { get; set; }
        public int AccountPrimaryContactNumber { get; set; }
        public string AccountPrimaryEmailAddress { get; set; }
        public int QuoteNumber { get; set; }
        public string QuoteDescription { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public string QuoteContactPhone { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactFullName { get; set; }
        public string ContactLetterSalutation { get; set; }
        public string RepFirstName { get; set; }
        public string RepLastName { get; set; }
        public string RepFullName { get; set; }
        public string RepTitle { get; set; }
        public string RepAddr1 { get; set; }
        public string RepAddr2 { get; set; }
        public string RepCity { get; set; }
        public string RepState { get; set; }
        public string RepOfficePhone { get; set; }
        public string RepEmail { get; set; }
        public string RepEmailSignature_Text { get; set; }
        public string RepEmailSignature_HTML { get; set; }
    }
}
