//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_StatementofAccountwithAgingTotals
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string AccountID { get; set; }
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool IsConsolidatedInvoice { get; set; }
        public string BillName { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillPostalCode { get; set; }
        public string BillCountry { get; set; }
        public string BillPhone { get; set; }
        public string BillContactName { get; set; }
        public string ARCustomerNumber { get; set; }
        public string AccountingCompanyID { get; set; }
        public Nullable<decimal> TotalInvoiced { get; set; }
        public Nullable<decimal> TotalCredit { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public int SalesRepNumber { get; set; }
        public string SalesRepName { get; set; }
        public Nullable<decimal> RepsPortion { get; set; }
    }
}
