//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVAccounts
    {
        public int ID { get; set; }
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string ContactName { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string AccountType { get; set; }
        public int RepNumber { get; set; }
        public string RepName { get; set; }
        public string HotNote { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public string AccountID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountOfOpenSOs { get; set; }
        public string SpecialInstructions { get; set; }
        public string AccountSource { get; set; }
        public string DefaultSystem { get; set; }
        public Nullable<System.DateTime> InitialContact { get; set; }
        public Nullable<System.DateTime> FirstInvoiceDate { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public string NumberOfEmployees { get; set; }
        public bool IsVendor { get; set; }
        public bool IsSubcontractor { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> LeadScore { get; set; }
        public int PrimaryContactNumber { get; set; }
        public Nullable<int> eAccountGroup { get; set; }
        public Nullable<int> eAccountProfile { get; set; }
        public Nullable<int> eContactGroup { get; set; }
        public Nullable<int> eSICCode { get; set; }
    }
}
