//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_CustomProjectFieldData
    {
        public int CustomFieldDefinitionKeyID { get; set; }
        public string CustomFieldCategoryName { get; set; }
        public string CustomFieldLabel { get; set; }
        public string CustomFieldValue { get; set; }
        public int ProjectKeyID { get; set; }
        public int OrdinalPosition { get; set; }
    }
}
