//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_Contacts
    {
        public int ContactNumber { get; set; }
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string ContactName { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string LetterSalutation { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string PrimaryFaxNumberFormatted { get; set; }
        public string PrimaryEmailAddress { get; set; }
    }
}
