//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_Contracts
    {
        public int ContractNumber { get; set; }
        public string ContactName { get; set; }
        public string Description { get; set; }
        public System.DateTime DateWritten { get; set; }
        public string Status { get; set; }
        public string ContractType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int HoursRemaining { get; set; }
        public int MinutesRemaining { get; set; }
        public double UnitsRemaining { get; set; }
        public decimal DollarsRemaining { get; set; }
        public int MeterRemaining { get; set; }
        public string OverUnderIndicator { get; set; }
        public string RepName { get; set; }
        public string RepEmailSignatureText { get; set; }
        public string RepEmailSignatureHTML { get; set; }
        public int BillToCust { get; set; }
        public string AccountName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
    }
}
