//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVRMAs_Filter2
    {
        public int ID { get; set; }
        public int RMAKeyID { get; set; }
        public string RMANumber { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string ShippingStatus { get; set; }
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string ContactName { get; set; }
        public string VendorPhone { get; set; }
        public int NumberOfItems { get; set; }
        public string Comments { get; set; }
        public bool Complete { get; set; }
        public string HoldingLocation { get; set; }
        public Nullable<int> CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerRMANumber { get; set; }
        public int BinLocation { get; set; }
        public Nullable<System.DateTime> DatePlacedOnRMA { get; set; }
        public Nullable<System.DateTime> ToVendorShipDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public int Received { get; set; }
        public Nullable<int> RMADetailKeyID { get; set; }
    }
}
