//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_RMAs
    {
        public int RMAKeyID { get; set; }
        public string RMAsRMANumber { get; set; }
        public Nullable<System.DateTime> RMADetailToVendorShipDate { get; set; }
        public Nullable<System.DateTime> RMADetailOutTime { get; set; }
        public Nullable<System.DateTime> RMADetailExpectedDate { get; set; }
        public Nullable<System.DateTime> RMADetailExpectedTime { get; set; }
        public Nullable<System.DateTime> RMAReceiptsReceivedDate { get; set; }
        public Nullable<int> RMADetailQuantity { get; set; }
        public Nullable<int> RMADetailQuantityReceived { get; set; }
        public Nullable<decimal> RMAReceiptsRepairCost { get; set; }
        public string RMADetailItemID { get; set; }
        public string RMADetailItemDescription { get; set; }
        public string RMASerialNumbersOriginalSerialNumber { get; set; }
        public string RMASerialNumbersReceivedSerialNumber { get; set; }
        public Nullable<int> RMADetailSONumber { get; set; }
        public Nullable<int> RMADetailContractNumber { get; set; }
        public string RMAsComments { get; set; }
        public string RMADetailDetailComment { get; set; }
        public string RMADetailPONumber { get; set; }
        public string RMADetailOutShipMethod { get; set; }
        public string RMADetailExpectedShipMethod { get; set; }
        public Nullable<System.DateTime> ContractsExpirationDate { get; set; }
        public string AccountName { get; set; }
        public string AccountID { get; set; }
        public string ServiceOrdersContactPhone { get; set; }
        public Nullable<System.DateTime> RMAReceiptsReceivedTime { get; set; }
        public string RMAReceiptsReceivedShipMethod { get; set; }
        public int RMAsVendorAccountNumber { get; set; }
        public string AccountContactName { get; set; }
        public string AccountsVendorAccountName { get; set; }
        public string ContactsVendorContactName { get; set; }
        public string ContactsVendorContactPhone { get; set; }
        public string AccountPhone { get; set; }
        public Nullable<System.DateTime> RMADetailReimbursementDate { get; set; }
        public Nullable<decimal> RMADetailVendorReimbursementAmount { get; set; }
        public Nullable<short> RMADetailItemSource { get; set; }
        public Nullable<int> RMADetailQuantityReturnedToStockOrCustomer { get; set; }
        public bool RMAsComplete { get; set; }
        public string RMAsContactName { get; set; }
        public System.DateTime RMAsDateTimeCreated { get; set; }
        public string RMAsVendorPhone { get; set; }
        public string RMAsHoldingLocation { get; set; }
        public int RMAsNumberOfItems { get; set; }
        public Nullable<decimal> ReplacementCostDifferential { get; set; }
        public Nullable<int> RMAReceiptsQuantity { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DatePlacedOnRMA { get; set; }
        public string RMADetailStatus { get; set; }
        public Nullable<int> RMADetailAccountNumber { get; set; }
    }
}
