//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_Accounts
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string AccountStatus { get; set; }
        public string AccountType { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string PrimaryFaxNumberFormatted { get; set; }
        public string PrimaryEmailAddress { get; set; }
        public string URL1 { get; set; }
        public string URL1Description { get; set; }
        public string URL2 { get; set; }
        public string URL2Description { get; set; }
        public string NumberOfEmployees { get; set; }
        public string Department { get; set; }
        public string RepName { get; set; }
        public string RepOfficePhone { get; set; }
        public string RepOfficePhoneExt { get; set; }
        public string RepFaxPhone { get; set; }
        public string RepFaxPhoneExt { get; set; }
        public string RepEmail1 { get; set; }
        public string RepEmailSignatureText { get; set; }
        public string RepEmailSignatureHTML { get; set; }
        public string PrimaryContactName { get; set; }
        public string PrimaryContactFirstName { get; set; }
        public string PrimaryContactTitle { get; set; }
        public string PrimaryContactDepartment { get; set; }
        public string PrimaryContactAddress1 { get; set; }
        public string PrimaryContactAddress2 { get; set; }
        public string PrimaryContactCity { get; set; }
        public string PrimaryContactState { get; set; }
        public string PrimaryContactPostalCode { get; set; }
        public string PrimaryContactCountry { get; set; }
        public string PrimaryContactPhoneNumber { get; set; }
        public string PrimaryContactFaxNumber { get; set; }
        public string PrimaryContactEmailAddress { get; set; }
        public string NotesMarketingSpecialInstructions { get; set; }
        public string NotesQuoteSpecialInstructions { get; set; }
        public string NotesServiceOrderSpecialInstructions { get; set; }
        public string NotesAccountSpecialInstructions { get; set; }
        public string NotesCreditHoldSpecialInstructions { get; set; }
    }
}
