//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_SalesbyManufacturer
    {
        public string ManufacturerName { get; set; }
        public string ItemID { get; set; }
        public int InvoiceNumber { get; set; }
        public string ItemDescription { get; set; }
        public double Quantity { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal TotalSellingPrice { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Status { get; set; }
    }
}
