//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_TokenData_DebitMemos
    {
        public int DebitMemoNumber { get; set; }
        public string Description { get; set; }
        public int PONumber { get; set; }
        public string RMANumber { get; set; }
        public string ConfirmedTo { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> VendorAccountNumber { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactName { get; set; }
        public string PODescription { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public string POStatus { get; set; }
        public Nullable<System.DateTime> POStatusDate { get; set; }
        public string RepName { get; set; }
        public string RepPhone { get; set; }
        public string RepEmail { get; set; }
        public string RepPhoneExt { get; set; }
        public string RepFaxExt { get; set; }
        public string RepFax { get; set; }
        public string RepSignatureText { get; set; }
        public string RepSignatureHTML { get; set; }
        public string AccountName { get; set; }
        public string AccountAddress1 { get; set; }
        public string AccountAddress2 { get; set; }
        public string AccountCity { get; set; }
        public string AccountState { get; set; }
        public string AccountPostalCode { get; set; }
        public string AccountCountry { get; set; }
        public string AccountPhone { get; set; }
        public string AccountFax { get; set; }
        public string AccountEmail { get; set; }
    }
}
