//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVCustomerInventory
    {
        public int ID { get; set; }
        public int CustomerInventoryKeyID { get; set; }
        public bool AssemblyFlag { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string SerialNumber { get; set; }
        public double Quantity { get; set; }
        public string Status { get; set; }
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public Nullable<System.DateTime> NextActionDate { get; set; }
        public string NextActionType { get; set; }
        public Nullable<System.DateTime> WarrantyExpiry { get; set; }
        public Nullable<System.DateTime> NextPMDate { get; set; }
        public Nullable<System.DateTime> LastPMDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> ContractNumber { get; set; }
        public string ContractType { get; set; }
        public int PrimaryRepNumber { get; set; }
        public string RepName { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> VendorAccountNumber { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<System.DateTime> MFGWarrantyExpiry { get; set; }
        public Nullable<int> OrigMeterReading { get; set; }
        public Nullable<int> CurrMeterReading { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string Comments { get; set; }
        public string ContractDescription { get; set; }
        public string ContractStatus { get; set; }
        public Nullable<bool> ContractActive { get; set; }
        public Nullable<System.DateTime> DatePurchasedFromVendor { get; set; }
    }
}
