//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_UnpaidInvoiceAging
    {
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> C0_30 { get; set; }
        public Nullable<decimal> C31_60 { get; set; }
        public Nullable<decimal> C61_90 { get; set; }
        public Nullable<decimal> C91_120 { get; set; }
        public Nullable<decimal> Over_120 { get; set; }
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string AR_Number { get; set; }
        public string Status { get; set; }
    }
}
