//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVTasks
    {
        public int ID { get; set; }
        public Nullable<int> TaskTypeImage { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> WholeStart { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> WholeEnd { get; set; }
        public int Age { get; set; }
        public string AccountName { get; set; }
        public string TaskComment { get; set; }
        public bool TaskCompletedIndicator { get; set; }
        public int ContactNumber { get; set; }
        public string ContactName { get; set; }
        public string AccountPrimaryPhoneNumberFormatted { get; set; }
        public int AccountNumber { get; set; }
        public string AccountsState { get; set; }
        public string ContactPrimaryPhoneNumberFormatted { get; set; }
        public int ScheduledForRepNumber { get; set; }
        public string RepName { get; set; }
        public string PriorityText { get; set; }
        public int PriorityNumber { get; set; }
        public string TaskType { get; set; }
        public string TaskAction { get; set; }
        public bool AlarmIndicator { get; set; }
        public Nullable<int> SONumber { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public int ScheduledByRepNumber { get; set; }
        public string ScheduledByRepName { get; set; }
        public string AccountsCity { get; set; }
        public Nullable<int> FKOpportunityKeyID { get; set; }
        public string ResourceName { get; set; }
        public string Subject { get; set; }
        public string Location { get; set; }
        public int AccountRepNumber { get; set; }
        public string AccountRepName { get; set; }
        public int PrivateIndicator { get; set; }
        public Nullable<int> LeadScore { get; set; }
        public Nullable<System.DateTime> SortStartDateTime { get; set; }
        public Nullable<System.DateTime> SortEndDateTime { get; set; }
    }
}
