//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_HPLVWorkOrders
    {
        public int ID { get; set; }
        public int WorkorderNumber { get; set; }
        public string WorkorderStatus { get; set; }
        public string AccountName { get; set; }
        public string ContactName { get; set; }
        public Nullable<System.DateTime> WorkorderDate { get; set; }
        public decimal AmountDue { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public Nullable<int> RepNumber { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<int> ContactNumber { get; set; }
    }
}
