//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_DBLVWorkItems
    {
        public string ItemTypeImage { get; set; }
        public int ID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> SONumber { get; set; }
        public string BriefDescription { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string DispatchBoardDescription { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> TimeReceived { get; set; }
        public string TechAssignedName { get; set; }
        public string ServiceZone { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<bool> HasTasks { get; set; }
        public Nullable<int> TaskStatusImage { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string TakenByName { get; set; }
        public string GeneralSymptoms { get; set; }
        public string SOType { get; set; }
        public string System { get; set; }
        public Nullable<int> EstimatedHrs { get; set; }
        public Nullable<int> EstimatedMins { get; set; }
        public Nullable<int> ContractNumber { get; set; }
        public string ContractRemaining { get; set; }
        public string InternalSOComments { get; set; }
        public Nullable<int> ProjectKeyID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> CreditHold { get; set; }
        public Nullable<System.DateTime> SLADeadline { get; set; }
        public Nullable<int> SOStatusRank { get; set; }
        public Nullable<int> SOPriorityRank { get; set; }
        public int AccountNumber { get; set; }
        public int ContactNumber { get; set; }
        public Nullable<int> TechAssigned { get; set; }
        public Nullable<int> TakenBy { get; set; }
        public Nullable<int> ReceivedDateAge { get; set; }
        public string ItemType { get; set; }
        public string FullPriority { get; set; }
        public Nullable<int> RepNumber { get; set; }
        public Nullable<int> TaskKeyID { get; set; }
        public Nullable<int> TaskAction { get; set; }
        public Nullable<int> TaskType { get; set; }
        public Nullable<int> TaskCompletedIndicator { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<int> StartDate { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndDate { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> TaskComment { get; set; }
        public Nullable<int> EmailKeyID { get; set; }
    }
}
