//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Portal_SOLogs
    {
        public int SOLogKeyID { get; set; }
        public int ContractNumber { get; set; }
        public int AccountNumber { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string RepName { get; set; }
        public int LogHours { get; set; }
        public int LogMinutes { get; set; }
        public int ElapsedHours { get; set; }
        public int ElapsedMinutes { get; set; }
        public string LogComment { get; set; }
        public string TimeLogReason { get; set; }
        public string Priority { get; set; }
        public int PriorityRank { get; set; }
        public bool Billable { get; set; }
        public bool Chargable { get; set; }
        public Nullable<decimal> LaborRate { get; set; }
        public int UsageInvoiceNumber { get; set; }
        public decimal LogReasonLaborRate { get; set; }
        public int RateType { get; set; }
        public int RateBasis { get; set; }
        public int Tech { get; set; }
        public Nullable<int> RoundingToNearestMinutes { get; set; }
        public Nullable<int> MinimumMinutes { get; set; }
        public int SONumber { get; set; }
        public byte AcceptanceStatus { get; set; }
        public double TimeConvertedToLaborItem { get; set; }
    }
}
