//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVTransfers
    {
        public int ID { get; set; }
        public int TransferNumber { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SONumber { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public Nullable<int> WorkOrderNumber { get; set; }
        public Nullable<int> DebitMemoNumber { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public int EnteredBy { get; set; }
        public string RepName { get; set; }
        public bool Printed { get; set; }
        public Nullable<int> eItemID { get; set; }
    }
}
