//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Serial
    {
        public string VendorAccountName { get; set; }
        public string AccountName { get; set; }
        public string PriceBookItemDescription { get; set; }
        public string PriceBookManufPartNumber { get; set; }
        public string PriceBookPartNumber { get; set; }
        public int SerialNumbersAccountNumber { get; set; }
        public string SerialNumbersItemID { get; set; }
        public string SerialNumber { get; set; }
        public string SerialNumbersStatus { get; set; }
        public Nullable<System.DateTime> SerialNumbersDateReceived { get; set; }
        public string SerialNumbersLocation { get; set; }
        public decimal SerialNumbersCost { get; set; }
        public string SerialNumbersDocAssignment { get; set; }
        public int FKSOPartsUsed { get; set; }
        public int FKSOPartsUsedAssemblyDetail { get; set; }
        public int FKQuoteDetail { get; set; }
        public int FKQuoteAssemblyDetail { get; set; }
        public int FKCreditMemoDetail { get; set; }
        public int FKCreditMemoAssemblyDetail { get; set; }
        public int FKDebitMemoDetail { get; set; }
        public int FKDebitMemoAssemblyDetail { get; set; }
        public int FKInvoiceAssemblyDetail { get; set; }
        public int FKInvoiceDetail { get; set; }
        public int FKCustomerInventoryAssemblyDetail { get; set; }
        public int FKCustomerInventory { get; set; }
    }
}
