//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_LVContracts
    {
        public int ID { get; set; }
        public int ContractNumber { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<System.DateTime> LastBillingDate { get; set; }
        public decimal ContractPrice { get; set; }
        public string ContractType { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string ACCOUNTPHONE { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string CONTACTPHONE { get; set; }
        public string RepName { get; set; }
        public int RepToCredit { get; set; }
        public string Reference { get; set; }
        public string Basis { get; set; }
        public string Remaining { get; set; }
        public string AssignedTech { get; set; }
        public Nullable<int> RepNumber { get; set; }
        public bool Active { get; set; }
        public string BillingCycle { get; set; }
        public System.DateTime DateWritten { get; set; }
        public bool AutoInvoice { get; set; }
        public bool AutoPay { get; set; }
    }
}
