//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_OpportunityResults
    {
        public int OpportunityKeyID { get; set; }
        public string OpportunityName { get; set; }
        public Nullable<decimal> TotalSellingPrice { get; set; }
        public string OpportunityStatus { get; set; }
        public string OpportunityType { get; set; }
        public string OpportunitySource { get; set; }
        public int OpportunityOwner { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public int StateOfOpportunity { get; set; }
        public string OpportunityStageDescription { get; set; }
        public string AccountName { get; set; }
        public string OwnerName { get; set; }
        public int AccountNumber { get; set; }
        public Nullable<int> ProbabilityPercent { get; set; }
    }
}
