//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_Portal_Contracts
    {
        public int BillToCust { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int ContractNumber { get; set; }
        public string ContractType { get; set; }
        public string timeremaining { get; set; }
        public string AccountName { get; set; }
        public bool Active { get; set; }
        public bool AutoInvoice { get; set; }
        public bool AutoPay { get; set; }
    }
}
