//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvw_AccountsWNoUncompletedTask
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string RepName { get; set; }
        public string AccountsPrimaryPhone { get; set; }
        public string AccountsPrimaryFax { get; set; }
        public int AccountsRepNumber { get; set; }
        public string AccountType { get; set; }
    }
}
