//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_LogInventoryCounts
    {
        public string LogTitle { get; set; }
        public string LogTypeInfo { get; set; }
        public System.DateTime LogTime { get; set; }
        public string LogSource { get; set; }
        public string Computer { get; set; }
        public string Description { get; set; }
        public int LogType { get; set; }
        public string BatchID { get; set; }
        public int RepNumber { get; set; }
        public string RepName { get; set; }
        public int id { get; set; }
    }
}
