//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_TaxInfo
    {
        public int AccountNumber { get; set; }
        public string GSTaxExemptID { get; set; }
        public bool GSTExempt { get; set; }
        public string SalesTaxCode { get; set; }
        public string TaxExemptCategory { get; set; }
        public string TaxExemptID { get; set; }
        public bool TaxFreight { get; set; }
        public bool TaxLabor { get; set; }
        public bool HideGSTaxRelatedInformation { get; set; }
    }
}
