//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_ExternalInvoiceCrossRef
    {
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string ARCustomerNumber { get; set; }
        public int BatchNumber { get; set; }
        public int ContractNumber { get; set; }
        public decimal Freight { get; set; }
        public decimal Deposit { get; set; }
        public string ExternalInvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public decimal GSTax { get; set; }
        public string PostingExceptionMemo { get; set; }
        public int SONumber { get; set; }
        public int QuoteNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public decimal TotalGrossSell { get; set; }
        public decimal TotalDollarsDiscounted { get; set; }
        public decimal Tax { get; set; }
        public decimal TotalAmountDue { get; set; }
        public decimal TradeIn { get; set; }
        public string RepName { get; set; }
        public bool HideGSTaxRelatedInformation { get; set; }
    }
}
