//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_SecurityInfoPerRep
    {
        public int RepNumber { get; set; }
        public string RepName { get; set; }
        public string SecurityCategory { get; set; }
        public string SecurityPrivilege { get; set; }
        public string Permission { get; set; }
        public bool Inactive { get; set; }
    }
}
