//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_WIPProjectPhases
    {
        public int ProjectKeyID { get; set; }
        public int ProjectPhaseKeyID { get; set; }
        public int OrdinalPosition { get; set; }
        public string ProjectPhaseStatus { get; set; }
        public int PercentComplete { get; set; }
        public decimal LaborAdjustment { get; set; }
        public decimal MaterialAdjustment { get; set; }
        public Nullable<int> RepNumber { get; set; }
        public string PhaseNote { get; set; }
        public int ProjectPhaseAssignmentsID { get; set; }
        public string ProjectPhase { get; set; }
        public Nullable<decimal> EstimatedLabor { get; set; }
        public Nullable<decimal> EstimatedMaterial { get; set; }
        public Nullable<int> EstimatedHrs { get; set; }
        public Nullable<int> EstimatedMins { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> TotalMinutes { get; set; }
        public Nullable<double> FilledCost { get; set; }
    }
}
