//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_TotalAmountDuePerAccount2
    {
        public int AccountNumber { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> Unappliedpayments { get; set; }
        public Nullable<decimal> ActualDue { get; set; }
    }
}
