//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InvoiceCommission
    {
        public string AccountName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<decimal> LaborAvg { get; set; }
        public Nullable<decimal> LaborEst { get; set; }
        public Nullable<decimal> LaborPosted { get; set; }
        public Nullable<decimal> LaborStd { get; set; }
        public Nullable<decimal> MaterialAvg { get; set; }
        public Nullable<decimal> MaterialEst { get; set; }
        public Nullable<decimal> MaterialPosted { get; set; }
        public Nullable<decimal> MaterialStd { get; set; }
        public Nullable<float> Commission { get; set; }
        public Nullable<float> CommissionNet { get; set; }
        public int ContractNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<int> InvoiceNumberCount { get; set; }
        public int QuoteNumber { get; set; }
        public string RepName { get; set; }
        public int SalesRep { get; set; }
        public string Status { get; set; }
        public decimal TotalNetSell { get; set; }
        public Nullable<int> RepNumber { get; set; }
    }
}
