//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_ReportExplorer
    {
        public string ReportTitle { get; set; }
        public string ReportFileName { get; set; }
        public string ReportDescription { get; set; }
        public string ReportClause { get; set; }
        public string ReportCategory { get; set; }
        public string SubCategory { get; set; }
        public int ReportID { get; set; }
    }
}
