//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InvoiceRevenueSummary
    {
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string SortAccount { get; set; }
        public string InvoicesARCustomerNumber { get; set; }
        public int BatchNumber { get; set; }
        public string BatchSort { get; set; }
        public string DocNum { get; set; }
        public int CreditMemoNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public string SortInvoice { get; set; }
        public System.DateTime DisplayDate { get; set; }
        public string SortDate { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal Freight { get; set; }
        public decimal GSTax { get; set; }
        public decimal TotalGrossSell { get; set; }
        public int OriginalInvoiceNumber { get; set; }
        public string RepName { get; set; }
        public int RestockingAmount { get; set; }
        public decimal SalesTax { get; set; }
        public string Status { get; set; }
        public decimal AmountDue { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public bool HideGSTaxRelatedInformation { get; set; }
        public string SOType { get; set; }
        public string Priority { get; set; }
        public string ServiceZone { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string StatusSortDate { get; set; }
        public string Source { get; set; }
        public int SONumber { get; set; }
        public int QuoteNumber { get; set; }
        public int ContractNumber { get; set; }
        public string PostingExceptionMemo { get; set; }
        public string DefaultSystem { get; set; }
        public float ProviderTaxRate { get; set; }
        public decimal ProviderTax { get; set; }
        public decimal TotalNetSell { get; set; }
        public Nullable<decimal> Special_Tax { get; set; }
    }
}
