//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InvoiceWCreditMemoRegister
    {
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public int AccountNumber { get; set; }
        public string SortAccount { get; set; }
        public string ARCustomerNumber { get; set; }
        public int BatchNumber { get; set; }
        public string BatchSort { get; set; }
        public string DocNum { get; set; }
        public int CreditMemoNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public string SortInvoice { get; set; }
        public System.DateTime DisplayDate { get; set; }
        public string SortDate { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> GSTax { get; set; }
        public Nullable<decimal> TotalGrossSell { get; set; }
        public int OriginalInvoiceNumber { get; set; }
        public string RepName { get; set; }
        public Nullable<decimal> RestockingAmount { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> TradeIn { get; set; }
        public bool HideGSTaxRelatedInformation { get; set; }
        public string SOType { get; set; }
        public string Priority { get; set; }
        public string ServiceZone { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string StatusSortDate { get; set; }
        public string Source { get; set; }
        public string PostingExceptionMemo { get; set; }
        public string DefaultSystem { get; set; }
        public string SOStatus { get; set; }
        public string SOInvStatus { get; set; }
        public string SOPostedStatus { get; set; }
    }
}
