//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InvoiceSales
    {
        public string AccountName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int SalesRep { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public string Status { get; set; }
        public string RepOnAccount { get; set; }
        public string RepOnInvoice { get; set; }
    }
}
