//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_ProjectChangeControl
    {
        public int ProjectKeyID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string Reference { get; set; }
        public string ProjectStatus { get; set; }
        public string AccountName { get; set; }
        public string ItemID { get; set; }
        public Nullable<double> QuoteQuantity { get; set; }
        public Nullable<decimal> QuoteTotalSellingPrice { get; set; }
        public Nullable<double> ServiceOrderQuantity { get; set; }
        public Nullable<decimal> ServiceOrderTotalSellingprice { get; set; }
        public Nullable<double> QuantityDifference { get; set; }
        public Nullable<decimal> TotalSellingpriceDifference { get; set; }
    }
}
