//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_PaymentsReceivedForConsolidatedInvoices
    {
        public int ConsolidatedInvoiceNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<int> ARPaymentsKeyID { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> ApplyToARAmount { get; set; }
    }
}
