//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InvoicePackingSlip
    {
        public int AccountNumber { get; set; }
        public int ContractNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public string PONumber { get; set; }
        public int QuoteNumber { get; set; }
        public int SONumber { get; set; }
        public int WorkOrderNumber { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> FKInvoiceDetail { get; set; }
        public string PrintItemorPartNum { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> InvoiceDetailKeyID { get; set; }
        public Nullable<int> InvoiceAssemblyDetailKeyID { get; set; }
        public string ItemDescription { get; set; }
        public string AssemblyItemID { get; set; }
        public string AssemblyItemDescription { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> QuantityFilled { get; set; }
        public Nullable<double> AssemblyQuantity { get; set; }
        public Nullable<double> AssemblyQuantityFilled { get; set; }
        public string Type { get; set; }
        public string AssemblyType { get; set; }
        public Nullable<bool> AssemblySerialized { get; set; }
        public Nullable<bool> DetailSerialized { get; set; }
        public string SourceDocument { get; set; }
    }
}
