//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_PickTicket
    {
        public Nullable<int> SONumber { get; set; }
        public int RepNumber { get; set; }
        public int ListView { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string AccountPhone { get; set; }
        public string ContactPhone { get; set; }
        public string CustomerPO { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string GeneralResolutions { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipContactName { get; set; }
        public string ShipPhoneNumber { get; set; }
        public string ShipCompanyName { get; set; }
        public Nullable<System.DateTime> TimeReceived { get; set; }
        public Nullable<System.DateTime> TimeRequested { get; set; }
        public string ItemDescription { get; set; }
        public string ItemID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> QuantityFilled { get; set; }
        public string Type { get; set; }
        public Nullable<int> SOPartsUsedKeyID { get; set; }
        public string AssemblyItemDescription { get; set; }
        public string AssemblyItemID { get; set; }
        public Nullable<double> AssemblyQuantity { get; set; }
        public string AssemblyType { get; set; }
    }
}
