//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_PriceBookListView
    {
        public string PartNumber { get; set; }
        public string ItemDescription { get; set; }
        public string Type { get; set; }
        public string ItemCategory { get; set; }
        public bool Taxable { get; set; }
        public string Bin { get; set; }
        public decimal BaseCost { get; set; }
        public decimal AverageCost { get; set; }
        public string ItemID { get; set; }
        public bool HotItem { get; set; }
        public string Features { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public int QuantityOnHand { get; set; }
        public int QuantityReserved { get; set; }
        public int QuantityOnOrder { get; set; }
        public int MinimumQuantity { get; set; }
        public decimal ManufacturerListPrice { get; set; }
        public string VendorItemID { get; set; }
        public string AccountName { get; set; }
        public string ItemSubCategory { get; set; }
        public string ManufacturerName { get; set; }
        public int PrimaryVendorAccountNumber { get; set; }
        public string Status { get; set; }
        public bool Serialized { get; set; }
        public string AssemblyType { get; set; }
        public Nullable<int> DiscountTier { get; set; }
        public bool Inactive { get; set; }
        public int PriceBookKeyID { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> DefaultPhaseKeyID { get; set; }
        public string DefaultProjectPhase { get; set; }
    }
}
