//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_AccountTaxCode
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string AccountType { get; set; }
        public string AccountStatus { get; set; }
        public string ARCustomerNumber { get; set; }
        public string TaxExemptID { get; set; }
        public string TaxExemptCategory { get; set; }
        public string GSTaxExemptID { get; set; }
        public bool HideGSTaxRelatedInformation { get; set; }
        public string SalesTaxCode { get; set; }
        public Nullable<float> TotalRate { get; set; }
    }
}
