//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_LastSONoteForServiceOrder
    {
        public int SONumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public string Topic { get; set; }
        public string TicketState { get; set; }
        public int TechAssigned { get; set; }
        public string TechAssignedName { get; set; }
    }
}
