//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_ProjectNotes
    {
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectNote { get; set; }
        public string RepName { get; set; }
        public string ContactName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string ContactsContactPhone { get; set; }
        public string AccountPhone { get; set; }
        public string ProjectStatus { get; set; }
        public System.DateTime ProjectDate { get; set; }
        public int ProjectKeyID { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
    }
}
