//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_SOContracts
    {
        public Nullable<int> ContractNumber { get; set; }
        public string Description { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int ContractHours { get; set; }
        public int ContractMinutes { get; set; }
        public decimal RatePerHour { get; set; }
        public int HoursRemaining { get; set; }
        public int MinutesRemaining { get; set; }
        public string OverUnderIndicator { get; set; }
        public string Basis { get; set; }
        public int MeterRemaining { get; set; }
        public float OverageChargePerClick { get; set; }
        public int MaxMeter { get; set; }
        public int CurrentMeter { get; set; }
        public int PeriodBaseClicks { get; set; }
        public decimal PeriodBaseHours { get; set; }
        public bool PeriodBaseMinutes { get; set; }
        public string PeriodUsageCycle { get; set; }
        public double UnitsRemaining { get; set; }
        public decimal DollarsRemaining { get; set; }
        public int WarningClicks { get; set; }
        public decimal MaxDollars { get; set; }
        public float WarningPercent { get; set; }
        public double MaxUnits { get; set; }
        public float ChargePerUnit { get; set; }
        public int SONumber { get; set; }
    }
}
