//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_ItemSoldToWhom
    {
        public string ItemID { get; set; }
        public int InvoiceNumber { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public string Status { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string RepName { get; set; }
    }
}
