//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_CustomCategories
    {
        public string CustomFieldCategoryName { get; set; }
        public int AppliesToID { get; set; }
        public string AppliesToName { get; set; }
        public string CustomFieldLabel { get; set; }
        public string CustomFieldDescription { get; set; }
        public int MaxLength { get; set; }
        public int MinValue { get; set; }
        public int MaxValue { get; set; }
        public int OrdinalPosition { get; set; }
    }
}
