//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_PriceBookView
    {
        public string ItemID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string ItemDescription { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Type { get; set; }
        public string ItemCategory { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Bin { get; set; }
        public string PictureFile { get; set; }
        public decimal BaseCost { get; set; }
        public decimal RepairCost { get; set; }
        public decimal LatestCost { get; set; }
        public decimal AverageCost { get; set; }
        public decimal TotalCost { get; set; }
        public decimal ManufacturerListPrice { get; set; }
        public string IncomeGlCode { get; set; }
        public string CostGlCode { get; set; }
        public Nullable<float> Margin { get; set; }
        public Nullable<float> Markdown { get; set; }
        public Nullable<float> Markup { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string Description { get; set; }
        public string PartNumber { get; set; }
        public Nullable<decimal> FlatPrice { get; set; }
        public string InventoryPicturePath { get; set; }
        public int PrimaryVendorAccountNumber { get; set; }
        public bool Serialized { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastSoldDate { get; set; }
    }
}
