//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InventoryValuation
    {
        public int LocatorKeyID { get; set; }
        public string Location { get; set; }
        public string LocationDescription { get; set; }
        public string LocationType { get; set; }
        public string ItemID { get; set; }
        public string PartNumber { get; set; }
        public string ItemDescription { get; set; }
        public string ItemCategory { get; set; }
        public string Bin { get; set; }
        public string ItemIDType { get; set; }
        public int Quantity { get; set; }
        public decimal AverageCost { get; set; }
        public Nullable<decimal> ExtendedAverageCost { get; set; }
        public decimal BaseCost { get; set; }
        public Nullable<decimal> ExtendedBaseCost { get; set; }
        public string SerialNumber { get; set; }
        public string STATUS { get; set; }
        public string SerialNumberLocation { get; set; }
    }
}
