//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_ReorderItems
    {
        public string LocatorItemID { get; set; }
        public Nullable<int> LocatorQuantity { get; set; }
        public string ItemDescription { get; set; }
        public int MinimumQuantity { get; set; }
        public int MaximumQuantity { get; set; }
        public float ReorderQuantity { get; set; }
        public int QuantityNeededtoFillOrders { get; set; }
        public string PartNumber { get; set; }
        public int QuantityOnOrder { get; set; }
        public string ItemID { get; set; }
        public string Type { get; set; }
        public bool Inactive { get; set; }
        public int QuantityReserved { get; set; }
        public int QuantityOnHand { get; set; }
        public Nullable<int> LocatorQuantityReserved { get; set; }
        public string WarehouseLocation { get; set; }
        public Nullable<int> LocatorQuantityOnOrder { get; set; }
    }
}
