//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_JobCostFromInvoices
    {
        public int AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string PrimaryFaxNumberFormatted { get; set; }
        public int InvoiceNumber { get; set; }
        public string ExternalInvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string ARCustomerNumber { get; set; }
        public string SourceDocument { get; set; }
        public int SONumber { get; set; }
        public int QuoteNumber { get; set; }
        public int ContractNumber { get; set; }
        public int ConsolidatedInvoiceNumber { get; set; }
        public Nullable<int> ProjectNumber { get; set; }
        public int MSPAgreementNumber { get; set; }
        public string Reference { get; set; }
        public decimal TotalAmountDue { get; set; }
        public decimal TotalDollarsDiscounted { get; set; }
        public string PostingExceptionMemo { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool IsConsolidatedInvoice { get; set; }
        public int SalesRep { get; set; }
        public string RepName { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public Nullable<int> InvoiceDetailKeyID { get; set; }
        public string DetailItemID { get; set; }
        public string eDetailItemDescription { get; set; }
        public string DetailType { get; set; }
        public Nullable<double> DetailQuantity { get; set; }
        public Nullable<decimal> DetailTotalPostedCost { get; set; }
        public Nullable<decimal> DetailTotalSellingPrice { get; set; }
        public Nullable<bool> DetailIsProgressiveInvoiceItem { get; set; }
        public Nullable<decimal> DetailTaxableAmount { get; set; }
        public Nullable<bool> DetailTaxable { get; set; }
        public Nullable<int> InvoiceAssemblyDetailKeyID { get; set; }
        public string AssemblyDetailItemID { get; set; }
        public string AssemblyDetailItemDescription { get; set; }
        public string AssemblyDetailType { get; set; }
        public Nullable<double> AssemblyDetailQuantity { get; set; }
        public Nullable<decimal> AssemblyDetailTotalCost { get; set; }
        public Nullable<decimal> AssemblyDetailTotalSellingPrice { get; set; }
        public Nullable<decimal> AssemblyDetailTaxableAmount { get; set; }
        public Nullable<bool> AssemblyDetailTaxable { get; set; }
        public string DetailAssemblyType { get; set; }
    }
}
