//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InvoiceCommissionUsingEstimatedCost
    {
        public string AccountName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public decimal EstimatedCostOnSourceDocument { get; set; }
        public Nullable<float> Commission { get; set; }
        public Nullable<float> CommissionNet { get; set; }
        public Nullable<float> CommissionProfit { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<int> InvoiceNumberCount { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public int QuoteNumber { get; set; }
        public string RepName { get; set; }
        public int SalesRep { get; set; }
        public string Status { get; set; }
        public decimal TotalNetSell { get; set; }
        public Nullable<int> RepNumber { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    }
}
