//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_GetWorkOrders
    {
        public int QuoteNumber { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string QuoteComments { get; set; }
        public string Shipper { get; set; }
        public string ShippingMethod { get; set; }
        public string AirbillNumber { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public string AccountID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public string PrimaryFaxNumberFormatted { get; set; }
        public string ShipName { get; set; }
        public string ShippingInstructions { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipContactName { get; set; }
        public string ShipPhone { get; set; }
        public string PackagingComments { get; set; }
        public string InternalComments { get; set; }
        public string ItemDescription { get; set; }
        public string PartNumber { get; set; }
        public Nullable<bool> QuoteAssemblyDetailSerialized { get; set; }
        public string Type { get; set; }
        public string AssemblyType { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> QuoteAssemblyDetailQuantity { get; set; }
        public string QuoteAssemblyDetailItemDescription { get; set; }
        public string QuoteAssemblyDetailItemID { get; set; }
        public Nullable<int> QuoteAssemblyDetailKeyID { get; set; }
        public string QuoteAssemblyDetailPriceBookPartNumber { get; set; }
        public Nullable<int> QuoteDetailQuoteNumber { get; set; }
        public string CustomerPurchaseOrder { get; set; }
        public decimal Freight { get; set; }
        public string Terms { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyState { get; set; }
        public string CompanyPostalCode { get; set; }
        public string CompanyCountry { get; set; }
        public string WorkOrderDisclaimer { get; set; }
        public string PrintItemorPartNum { get; set; }
        public int WorkorderNumber { get; set; }
        public Nullable<System.DateTime> WorkorderDate { get; set; }
        public string BillingComments { get; set; }
        public Nullable<int> QuoteDetailLineNumber { get; set; }
        public Nullable<int> QuoteDetailKeyID { get; set; }
        public string Bin { get; set; }
        public string ItemID { get; set; }
        public Nullable<bool> Serialized { get; set; }
        public string QuoteDetailPriceBookAssemblyType { get; set; }
    }
}
