//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_InvoiceItemID2
    {
        public int InvoiceNumber { get; set; }
        public string ItemID { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Type { get; set; }
        public int AccountNumber { get; set; }
        public int Code { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> TotalPostedCost { get; set; }
        public Nullable<double> TotalSellingPrice { get; set; }
        public Nullable<int> InvoiceDetailKeyID { get; set; }
        public Nullable<double> Profit { get; set; }
        public int SONumber { get; set; }
        public int QuoteNumber { get; set; }
        public int WorkOrderNumber { get; set; }
        public int ContractNumber { get; set; }
        public Nullable<double> Margin { get; set; }
        public string AccountName { get; set; }
        public Nullable<bool> IsRepairLevel { get; set; }
        public string ItemDescription { get; set; }
        public string Status { get; set; }
        public string RepName { get; set; }
        public Nullable<int> RepNumber { get; set; }
        public string ItemCategory { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string CostGLCode { get; set; }
        public string IncomeGLCode { get; set; }
        public string CostDebitAccount { get; set; }
        public string CostCreditAccount { get; set; }
        public string IncomeDebitAccount { get; set; }
        public string IncomeCreditAccount { get; set; }
    }
}
