//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_TechUtilization
    {
        public string RepName { get; set; }
        public string Status { get; set; }
        public int SONumber { get; set; }
        public int Tech { get; set; }
        public string TimeLogReason { get; set; }
        public int LogHours { get; set; }
        public int LogMinutes { get; set; }
        public bool Chargable { get; set; }
        public bool Billable { get; set; }
        public decimal LogReasonLaborRate { get; set; }
        public System.DateTime StartDateTime { get; set; }
    }
}
