//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_FIFOLIFO
    {
        public string ItemDescription { get; set; }
        public string InventoryCostingMethod { get; set; }
        public int FiFoLiFOKeyID { get; set; }
        public string ItemID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public int ReceiptQuantity { get; set; }
        public decimal ReceiptUnitCost { get; set; }
    }
}
