//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_invoice_cbi_value_initial_sale
    {
        public int AccountNumber { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Status { get; set; }
        public decimal TotalNetSell { get; set; }
        public decimal TotalPriceCredited { get; set; }
        public int IsConsolidatedInvoice { get; set; }
        public int CBID { get; set; }
    }
}
