//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_ContractInvoiceBillingDetail
    {
        public Nullable<int> BillToCust { get; set; }
        public string Description { get; set; }
        public bool HideGSTaxRelatedInformation { get; set; }
        public decimal Amount { get; set; }
        public int ContractNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Account_Number { get; set; }
        public string Account_Name { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> GS_Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string AR_Customer_Number { get; set; }
        public string Billing_Cycle { get; set; }
    }
}
