//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_RMAs
    {
        public int RMAKeyID { get; set; }
        public string RMANumber { get; set; }
        public Nullable<System.DateTime> ToVendorShipDate { get; set; }
        public Nullable<System.DateTime> ToVendorShipTime { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> ExpectedTime { get; set; }
        public Nullable<System.DateTime> ReceiptsReceivedDate { get; set; }
        public Nullable<int> DetailQuantity { get; set; }
        public Nullable<int> DetailQuantityReceived { get; set; }
        public int RepairCost { get; set; }
        public string DetailItemID { get; set; }
        public string DetailItemDescription { get; set; }
        public string OriginalSerialNumber { get; set; }
        public string ReceivedSerialNumber { get; set; }
        public Nullable<int> DetailSONumber { get; set; }
        public Nullable<int> ASDetailContractNumber { get; set; }
        public string Comments { get; set; }
        public string DetailComment { get; set; }
        public string PONumber { get; set; }
        public string ToVendorShipMethod { get; set; }
        public string ExpectedShipMethod { get; set; }
        public Nullable<System.DateTime> ContractsExpirationDate { get; set; }
        public string AccountName { get; set; }
        public string AccountID { get; set; }
        public string ServiceOrdersContactPhone { get; set; }
        public string ReceivedShipMethod { get; set; }
        public int VendorAccountNumber { get; set; }
        public string AccountContactName { get; set; }
        public string VendorAccountName { get; set; }
        public string VendorContactName { get; set; }
        public string VendorContactPhone { get; set; }
        public string PrimaryPhoneNumberFormatted { get; set; }
        public Nullable<System.DateTime> ReimbursementDate { get; set; }
        public Nullable<decimal> VendorReimbursementAmount { get; set; }
        public Nullable<short> DetailItemSource { get; set; }
        public Nullable<int> QuantityReturnedToStockOrCustomer { get; set; }
        public bool Complete { get; set; }
        public string ContactName { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
        public string VendorPhone { get; set; }
        public string HoldingLocation { get; set; }
        public int NumberOfItems { get; set; }
        public Nullable<decimal> ReplacementCostDifferential { get; set; }
        public Nullable<int> ReceiptsQuantity { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DatePlacedOnRMA { get; set; }
        public string DetailStatus { get; set; }
        public Nullable<int> DetailAccountNumber { get; set; }
        public Nullable<int> FKRMADetail { get; set; }
        public Nullable<int> FKRMAReceipts { get; set; }
        public Nullable<System.DateTime> ReceiptsReceivedTime { get; set; }
        public Nullable<int> RMAReceiptsKeyID { get; set; }
        public Nullable<int> RMADetailKeyID { get; set; }
    }
}
