//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_TimeTransactions
    {
        public int KeyID { get; set; }
        public int RecordType { get; set; }
        public int SONumber { get; set; }
        public int Tech { get; set; }
        public string TimeLogReason { get; set; }
        public string LogComment { get; set; }
        public int InvoiceableHours { get; set; }
        public int InvoiceableMinutes { get; set; }
        public int ActualHours { get; set; }
        public int ActualMinutes { get; set; }
        public int UtilizationHours { get; set; }
        public short UtilizationMinutes { get; set; }
        public int Chargable { get; set; }
        public Nullable<bool> Billable { get; set; }
        public float UnitFactor { get; set; }
        public double TotalUnits { get; set; }
        public int UsageInvoiceNumber { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public double TimeConvertedToLaborItem { get; set; }
        public decimal LogReasonLaborRate { get; set; }
        public int ContractNumber { get; set; }
        public string RepName { get; set; }
        public string ViewKeyID { get; set; }
        public string TechInitials { get; set; }
        public Nullable<int> TotalTimeInMinutes { get; set; }
        public int RepNumber { get; set; }
        public string Status { get; set; }
        public long PrintID { get; set; }
        public byte AcceptanceStatus { get; set; }
        public string RejectedStatusReason { get; set; }
        public int AcceptOrRejectedByNumber { get; set; }
        public string AcceptOrRejectedByName { get; set; }
    }
}
