//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermaNet.Tigerpaw
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwr_PurchaseOrdersbySONumber
    {
        public int PoNumber { get; set; }
        public Nullable<int> ProjectKeyID { get; set; }
        public int SONumber { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public string ItemID { get; set; }
        public string ItemDescription { get; set; }
        public string POStatus { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<long> UniquePODetailKey { get; set; }
        public int PODetailKeyID { get; set; }
        public double QuantityOrdered { get; set; }
        public Nullable<double> QuantityReceived { get; set; }
        public double QuantityCancelled { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Shipper { get; set; }
        public string ShipperTrackingNumber { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<System.DateTime> DateExpected { get; set; }
        public int VendorAccountNumber { get; set; }
        public string VendorName { get; set; }
    }
}
